### ISSUE TITLE
Lazy blocks don't update on ajax cart add (native)

### ISSUE THREAD

**Issue by devzorg** [GordonLesti/Lesti_Fpc#102]
But it works if a native Add to cart used without ajax
so the requests is:
`http://example.com/checkout/cart/add/uenc/[base64]/product/920/?isajaxcart=true&ajaxlinks=1`
and
`http://example.com/checkout/cart/add/uenc/[base64]/product/920/`

I have tried to add params to except but it didn't help.
Handler `checkout_cart_add` exists in the Refresh actions field in the settings of FPC

**Comment by rafaelpatro** [comment]
The same happens to me.
Usually lazy blocks are working fine. But when I send the same request by ajax, that blocks are not refreshed.
Response is refreshed. But the next page load has no refreshed blocks.
So the second page load shows up the lazy blocks refreshed.

Mage 1.9.1.0
Extension: https://github.com/calinsargan/HardikAjaxCart-2.0.1

**Comment by GordonLesti** [comment]
Fpc is observing the event `controller_action_postdispatch` and checking for refresh action. If your ajax add to cart didn't do that, maybe the easiest solution would be to change to dynamic block instead.

**Comment by rafaelpatro** [comment]
Hi Gordon.
Yes it was my first option. After setting __minicart_head__ as dynamic everything worked as expected.

Could I remove __checkout_cart_add__ from __Refresh Action__ in order to improve the cache?
Same for __checkout_cart_delete__ and __checkout_cart_updatePost__?

**Comment by GordonLesti** [comment]
yes, you can remove them.
