### ISSUE TITLE
Lesti_Fpc keys not stored (Redis)

### ISSUE THREAD

**Issue by wolololo** [GordonLesti/Lesti_Fpc#107]
I'm using Magento CE 1.9.1 and Lesti_Fpc latest is still stored in /var/cache. Or configured incorrectly?

Lesti cache tree:
>>>> http://vpaste.net/8brZJ

redis keys (db=0):
>>>> http://vpaste.net/NZppF

/www/magento/app/etc/fpc.xml
>>>> http://vpaste.net/nkXsE

/www/magento/app/etc/local.xml
>>>> http://vpaste.net/PhZdi

cc @GordonLesti

**Comment by GordonLesti** [comment]
The first fpc.xml has no redis configured and the second fpc.xml has no fpc-tag.

**Comment by wolololo** [comment]
I remove the fpc tag and clean up all cache.

/www/magento/app/etc/fpc.xml
>>> http://vpaste.net/mgphM

I'm sure I config it right, but still stored in /var/cache. I connect to a Redis instance using a Unix Socket and where looks fully unconfigured?
