### ISSUE TITLE
Customer session cached

### ISSUE THREAD

**Issue by engrKaka** [GordonLesti/Lesti_Fpc#110]
In a custom module I had added a block to product page, I also added that block to dynamic_blocks in Lasti_Fpc config.xml file. 
In that block's phtml file, I am using
if(Mage::getSingleton('customer/session')->isLoggedIn()) 
to check if the customer is logged in or not (to show different button for logged in vs not logged in)
but the problem is when i browse the product page before login, then after login the page still shows content for the not logged in customers.
Can anybody help me guide me, how to tackle this and which block to include in dynamic block list?

**Comment by GordonLesti** [comment]
Hello,
the config.xml is just for the default values of the configs after installation. Please do not edit the config.xml. You have to edit the configs of the Magento Backend.

**Comment by engrKaka** [comment]
Apologies for making such a silly mistacke, actually i couldn't found some tutorials on how to do hole punching of FPC in community edition.
