### ISSUE TITLE
After installing Shop Crashed

### ISSUE THREAD

**Issue by taracho** [GordonLesti/Lesti_Fpc#113]
Hello,

After installing my Shop just Crashed.

In System.Log im getting this warning: Warning: include() [<a href='function.include'>function.include</a>]: Failed opening ........includes/src/Lesti_Fpc_Model_Observer_Save.php' for inclusion (include_path='/............./includes/src:.:/usr/share/php53/PEAR')  in /........./includes/src/Varien_Autoload.php on line 94

I Hope you can Help me.

Thanks

**Comment by GordonLesti** [comment]
Hello,
please disable or refresh Magento compiler.

**Comment by taracho** [comment]
how can i do this now?

**Comment by taracho** [comment]
Thanks 
i will disable the compile via ssh

**Comment by taracho** [comment]
It worked! ;)

thank you  v m
