### ISSUE TITLE
Site cache crawler

### ISSUE THREAD

**Issue by Nasatya** [GordonLesti/Lesti_Fpc#116]
Is there any way I could crawl my web store every night and store fcp cache? LIke a cron job running a script that runs your extension. The site is really fast right now, I am only missing the speed on sites that have never been visited before and are not cached yet with fcp.
Is there a script that already exists or how can I do that?

Thank you very much.

**Comment by GordonLesti** [comment]
Hello @Nasatya 
I'm sorry, I have no solution for your problem. There are Fpc-crawlers on the market, but I'm not sure how good they are. Lesti_Fpc is a little bit special, cause it would need a session based crawler.
Can I close this issue?

**Comment by Nasatya** [comment]
Yes you can close this issue, I found the solution, thank you.

**Comment by Mic2005** [comment]
@nasatya what solution did you found for cachewarmer?

Micha

2015-05-19 11:42 GMT+02:00 Nasatya <notifications@github.com>:

**Comment by Webmasterei** [comment]
For everyone looking for a solution... here's some offers: http://www.webguys.de/magento/adventskalender/turchen-08-magento-cache-warming-und-weitere-caching-tricks/
