### ISSUE TITLE
Undefined index: wjkqydzjyknjhzie3

### ISSUE THREAD

**Issue by DegrizNet** [GordonLesti/Lesti_Fpc#117]
Hello,

my error tracking reports me the next error. Do you know what could be the problem?

Error: Undefined index: wjkqydzjyknjhzie3 in /public_html/app/code/core/Mage/Cms/controllers/IndexController.php on line 134

Thank you for help!

**Comment by GordonLesti** [comment]
Hello,
this doesn't look related to Fpc. But if you say me which Magento version you run, maybe I have hint for you what the reason for this problem can be.

**Comment by DegrizNet** [comment]
hei.. thank you for fast replay. This error we get on Magento 1.9.1 and it goes away if we disable fpc cache so I thought thing are related.

**Comment by GordonLesti** [comment]
But `app/code/core/Mage/Cms/controllers/IndexController.php` has no line `134` https://github.com/OpenMage/magento-mirror/blob/1.9.1.0/app/code/core/Mage/Cms/controllers/IndexController.php
Can it be, that you have modified core files?

**Comment by DegrizNet** [comment]
Ok I see this code is not part of Magento ..how it could get here I need to find out. Sorry for wasting your time. 

Thank you for great module!

p.s. I left 5 star review on Magento ;)
