### ISSUE TITLE
Magento 1.9 filters broken

### ISSUE THREAD

**Issue by Demon5332** [GordonLesti/Lesti_Fpc#121]
When I have fpc enabled things like shop by categories and price/manufacturer don't work.

**Comment by GordonLesti** [comment]
I hope this [post](https://gordonlesti.com/lestifpc-and-layered-navigation/) will help you.

**Comment by Demon5332** [comment]
that should really be included in docs or have price, manufacturer,cat in there by default since these are in stock cart and something that most people use

**Comment by GordonLesti** [comment]
Yes, that would be nice. There is already a open [Pull request](https://github.com/GordonLesti/Lesti_Fpc/pull/105) for filterable attributes.
