### ISSUE TITLE
Cache not flushed with memcached

### ISSUE THREAD

**Issue by SergioViteri** [GordonLesti/Lesti_Fpc#122]
When having lots of items, memcached is not being flushed when updating product. The only way I found to flush it is clearing everything with flush_all in memcache. Anyone else with this problem?

**Comment by gaiterjones** [comment]
I am seeing a similar problem where the cache is not flushed at all when memcache is enabled. Cache Management -> FPC refresh does not refresh the lesti cache. I have to flush Magento Cache / Cache Storage. I also saw that cached Memcache pages were not ageing out and automatically refreshing, one cached page was 5 days old and still cached.

**Comment by Mic2005** [comment]
I always flush the cache with orange buttons after saving page. Because
otherwise I don't see the updated menu or page. I use Redis. How can we
test if fpc clear this item?
Op 1 jun. 2015 10:36 schreef "gaiterjones" <notifications@github.com>:

**Comment by SergioViteri** [comment]
It seems that memcached does no support tags so magento is unable to flush a single page. We should flush the whole cache everytime we make changes to any product.
Our solution: we have switched our fpc cache to redis and for the moment it seems to work smoothly ;)
