### ISSUE TITLE
Automatically add layered navigation parameters?

### ISSUE THREAD

**Issue by Zyles** [GordonLesti/Lesti_Fpc#126]
I get that you can add layered navigation URL parameters in the configuration. But this is a real hassle every single time we add a new attribute etc.

Can it not be possible to add these parameters to the configuration automatically?

If we add a new attribute and tell it to be included in layered navigation with the settings, it would be nice if Lesti can figure out that "Hey, they want to use this in layered navigation, let's exclude it in the configuration"...

**Comment by GordonLesti** [comment]
https://github.com/GordonLesti/Lesti_Fpc/pull/105

**Comment by sprankhub** [comment]
I think this issue can be closed, because this is now implemented.

**Comment by GordonLesti** [comment]
yes, thank you @sprankhub
