### ISSUE TITLE
HTTP and HTTPS

### ISSUE THREAD

**Issue by rmalenko** [GordonLesti/Lesti_Fpc#130]
Is it possible to cache different pages by HTTP and HTTPS protocols?
HTTPS URL has a link to css, js, images by on HTTP. This is broken a page in a browser.

**Comment by GordonLesti** [comment]
Hello @rmalenko normally this should happen here in [Lesti_Fpc_Helper_Data::_getParams](https://github.com/GordonLesti/Lesti_Fpc/blob/1.3.7/app/code/community/Lesti/Fpc/Helper/Data.php#L70). Fpc differs with the port. Is it possible to have HTTP and HTTPS over the same port with something in front of the webserver?

**Comment by MarkSimon** [comment]
Hello Gordon Lesti.

Sorry for jumping into this old conversation. But I currently have a similar problem like rmalenko.
I am using *SSL offloaded* in a *load balancer*. In my case I use HTTP from the load balancer to the web server(s).
Magento it self is able to handle that when I configure `web/secure/offloader_header`

To solve it I added `Mage::app()->getStore()->isCurrentlySecure()`into the `$params` in `Lesti_Fpc_Helper_Data::_getParams`.
Then it does work like a charm even if SSL is (also) being handled on port 80.

I would appreciate if that can find a way into the official version.

**Comment by GordonLesti** [comment]
https://github.com/GordonLesti/Lesti_Fpc/pull/160
