### ISSUE TITLE
Lesti FPC does not work with Magento 1.7 and Magento 1.9.1

### ISSUE THREAD

**Issue by paras89** [GordonLesti/Lesti_Fpc#135]
I observed that even through Lesti_Fpc was enabled it did not cache content.

The reason is that there is a mismatch between the key with which it saves the entry in cache and the key it tries to retrieve content with.

**Compare:**

###### Lesti_Fpc_Helper_Data::getKey($postfix = '_page') (used for reads)

**with**

###### Mage_Core_Model_Cache::_id($id) (used for writes)

Magento's core cache model does an strtoupper to id before using it as a key, while Lesti_Fpc doesn't captialize it's key for reads.

###### Fix: Lesti_Fpc_Helper_Data::getKey($postfix = '_page') should return:

return strtoupper(sha1($this->_getParams()) . $postfix);

**Comment by GordonLesti** [comment]
Hello @paras89 
I thank you for your investigation, but I know that Lesti_Fpc works on 1.7 and 1.9 cause I have tried it. The function `Mage_Core_Model_Cache::_id` is not only used for writes, also for reads.

**Comment by paras89** [comment]
Ok, for one of my clients I had to use the above code change to fix it because the capitalization was different. Checked the code to retrieve keys in Magento 1.9 and it has similar code. 

Check: https://github.com/GordonLesti/Lesti_Fpc/blob/master/app/code/community/Lesti/Fpc/Model/Observer.php
 Lesti_Fpc_Model_Observer::controllerActionLayoutGenerateBlocksBefore, The module calls: 
$key = Mage::helper('fpc')->getKey();
            if ($object = $fpc->load($key)) {....}

So as you can see, for reads it gets the key from the fpc helper rather than using Mage_Core_Model_Cache::_id

**Comment by GordonLesti** [comment]
yes, the key is always build by this helper. But I'm not sure why you think that this is a problem.

**Comment by paras89** [comment]
Ah I see what you meant.  $fpc->load($key) does internally make use of Mage_Core_Model_Cache::_id
and it works on a vanilla Magento 1.9 install. Sorry for the bother!

**Comment by GordonLesti** [comment]
no problem, you are welcome.
