### ISSUE TITLE
Manadev SEO Layered Navigation

### ISSUE THREAD

**Issue by ollyboy** [GordonLesti/Lesti_Fpc#136]
When using Fix Lesti_Fpc + Manadev SEO Layered Navigation this post indicates a patch is needed

https://gist.github.com/peterjaap/7c431c962a09538c3538

There is also a blog post here

http://www.manadev.com/blog/magento-layered-navigation-with-lesti-full-page-cache/

Is the patch still needed and are the blog post configs still correct?

**Comment by GordonLesti** [comment]
* I would recommend to use the event `fpc_helper_collect_params` instead of the patch.
* I'm not sure if the blog post is still correct, cause this is a paid extension and I don't have access to the source
