### ISSUE TITLE
Compatibility with NGINX and PHP-FPM

### ISSUE THREAD

**Issue by deniscass** [GordonLesti/Lesti_Fpc#137]
Hi Guys,

I'm install Lesti_Fpc in my staging site and i get a strange behavior. My setup is NGINX+PHP-FPM+MEMCACHED+Magento 1.9.2.1 and i'm getting a issue when Lesti_Fpc is enabled. Some footer static blocks change the position or get duplicated positions in footer and header. The generated HTML is correct, but the blocks get a wrong position breaking my design. Some tips to avoid this? I attempt update PHP to 5.5, disable memcached or other caches in magento but without success... I need the great performance when Lesti_Fpc was enabled in my website.

**Comment by GordonLesti** [comment]
Hello @deniscass 
waht are your configs for dynamic/lazy blocks?

**Comment by deniscass** [comment]
Hi Gordon, 

I get defaults block config and no chance anything. But, I have many Ajax cart plugins, a custom layout. You can check my production site: https://www.cervejaexpress.com.br with Fpc disabled.

-----Mensagem Original-----
De: "Gordon Lesti" <notifications@github.com>
Enviada em: ‎25/‎08/‎2015 06:06
Para: "GordonLesti/Lesti_Fpc" <Lesti_Fpc@noreply.github.com>
Cc: "deniscass" <deniscassiano@gmail.com>
Assunto: Re: [Lesti_Fpc] Compatibility with NGINX and PHP-FPM (#137)

Hello @deniscass 
waht are your configs for dynamic/lazy blocks?

**Comment by deniscass** [comment]
Hi Gordon, please check my configs:

Cachable Actions:

cms_index_index,
cms_page_view,
catalog_product_view,
catalog_category_view

Dynamic Blocks:

messages,
global_messages,
global_notices,
right.reports.product.viewed


Refresh Actions:

checkout_cart_add,
checkout_cart_delete,
checkout_cart_updatePost,
catalog_product_compare_add,
catalog_product_compare_clear,
catalog_product_compare_remove,
wishlist_index_add,
wishlist_index_remove,
wishlist_index_update,
wishlist_index_allcart,
wishlist_index_configure,
checkout_onepage_success,
poll_vote_add



Lazy Blocks:

top.links,
cart_sidebar,
catalog.compare.sidebar,
wishlist_sidebar,
welcome,
minicart_head,
right.poll



Uri Params:

id,
category,
page_id,
p,
limit,
dir,
order,
mode


Miss Uri Params

no_cache=/^1$/,
limit=/^([0-9]+)|(all)$/,
dir=/^[0-9a-z_]+$/,
order=/^[0-9a-z_]+$/,
mode=/^[0-9a-z_]+$/,
___store=/^[a-z]{1}[0-9a-z_]*$/

**Comment by GordonLesti** [comment]
Looks fine to me.
You can contact me via email if you need more help.
