### ISSUE TITLE
Does this work with HHVM ?

### ISSUE THREAD

**Issue by bgui** [GordonLesti/Lesti_Fpc#139]
I tried using Fpc on HHVM 3.8, but seems there is a problem in the Model/Fpc load function.

**Comment by janw-oostendorp** [comment]
It should.
[here](https://support.hypernode.com/knowledgebase/configure-lestifpc/) is a hosting company which uses HHVM.  
And this article explains configuring FPC with Redis on HHVM.  
I don't have experience with HHVM hopes it helps you.

**Comment by rmalenko** [comment]
I would like to confirm it.
ERR (3): Warning: data error in /app/code/community/Lesti/Fpc/Model/Fpc.php on line 117
Something with gzip is wrong

**Comment by GordonLesti** [comment]
@rmalenko why didn't you disable gzcompress if your setup didn't support it?

**Comment by rmalenko** [comment]
@GordonLesti thank you for answer. I had tried to set
```
<compress_data>1</compress_data>
<compress_tags>1</compress_tags>
```
to zero and disabled compression in back-end.

Could you prompt me how it do better?

However local.xml
```
...
<redis_session>
<compression_threshold>2048</compression_threshold>
<compression_lib>gzip</compression_lib>
...
```

Is this mean that my server supported gzcompress?

**Comment by GordonLesti** [comment]
The option for gzcompress in the configs of Fpc is only for file cache. The cache backend redis has it's own compression logic.

**Comment by rmalenko** [comment]
I mean that session are cached and gzipped under HHVM or PHP-FPM.
Lesti_Fpc perfectly works only with PHP-FPM. 

P.S.
Thank you for this plugin! :+1:

**Comment by salubrium** [comment]
We use HHVM with Lesti perfectly fine but using file backend, not redis backend.

**Comment by aftabnaveed** [comment]
I am using it with HHVM and Redis and works perfectly fine.

**Comment by rmalenko** [comment]
@aftabnaveed could you show your hhvm config, please?

**Comment by ninteh** [comment]
@rmalenko have you considered compiling php7-fpm beta? I'm using it just for our admin section of magento (which it sped up by about 10x for product admin etc) it did work with lesti fpc on the frontend during testing, the only extension that didn't work was an Amasty discount rule module we use. So I route frontend to php5-fpm and admin to php7-fpm :]

**Comment by rmalenko** [comment]
@ninteh I am agree, however client wanted HHVM :) My tests show me that even PHP5.6 is very similar to HHVM.

**Comment by ninteh** [comment]
@rmalenko that's cool then :) I noticed HHVM sped up Magento admin a lot for us, but so does php7 :D frontend not much difference, except some 100ms off response time which can help on high traffic. cheers!

**Comment by GordonLesti** [comment]
I will close the issue.
