### ISSUE TITLE
Serve home page“instantly”

### ISSUE THREAD

**Issue by PedroKTFC** [GordonLesti/Lesti_Fpc#142]
(I originally asked this here: http://magento.stackexchange.com/questions/82004/serve-home-page-from-lesti-fpc-instantly but it was suggested I should ask this here so voila!)

I wonder if there's a way to serve a cached version of a home page more or less instantly so that if the url requested is the home page, the server serves directly from the cache without doing any further checks.

My home page is pretty static and I would like a cache of it to be served every time. If I change it, I'll rebuild the cache manually.

**Comment by Schrank** [comment]
The homepage is a cms page, therefore I would assume it is served from full page cache with LestiFPC, did you try it?

**Comment by PedroKTFC** [comment]
I use Lesti FPC so it is served from the cache but I'd like to try something like a check in index.php if it's the home page and immediately serve the cached version always to see how much that speeds things up.

**Comment by GordonLesti** [comment]
Did you have no mini cart or welcome message on your homepage?

**Comment by PedroKTFC** [comment]
Apologies for the slow reply, I've been on holiday. My home page has nothing "dynamic" that should really vary (the only thing would be the "My Cart" link and that's a bridge to worry about later). I use the new products widget on it but I don't add new products frequently so can rebuild the cache whenever I do.

**Comment by GordonLesti** [comment]
I'm sorry, but FPC didn't work outside of Magento. But if your homepage is completely static, the easiest way would be a index.html in the webroot (not recommended)?

**Comment by PedroKTFC** [comment]
Sorry, I probably wasn't clear enough. You can see my site here: mylingerie-buntingford.co.uk. It's entirely in Magento and I use Lesti FPC. As I said at the start, I was simply curious if there's a way of serving the home page as "instantly" as possible as obviously that's likely to be the first page people will be directed to. After that, I'd hope they'd be a little more patient if they're interested in what's there.

**Comment by GordonLesti** [comment]
I tested it, and I would say 330 ms for TTFB is very good in my eyes.

**Comment by PedroKTFC** [comment]
Not bad I'd say! ;) I guess I was trying to be greedy!
