### ISSUE TITLE
Block name added to dynamic blocks not working 

### ISSUE THREAD

**Issue by Taral-Patoliya** [GordonLesti/Lesti_Fpc#143]
I have added a block on the homepage cms using 
{{block type="zbullionmoney/bullionprices" name_in_layout="price_update"}}
and added price_update in the dynamic blocks list,
But Instead of ignoring the caching , the block does not display at all,

Same with the global messages, it loads the blocks in  wrong order

**Comment by GordonLesti** [comment]
I wouldn't recommend to have dynamic things in cms pages, but I know that it's sometimes the only solution. Please do not forget to add you block also via any layout.xml to the `cms_page_view` handle in a not visible way.

**Comment by jotao23** [comment]
Hi Gordon

 

Please, can you remove our email of your distribution list  @newstri.com

 

Cordial Saludo / Best Regards / Cordialment / Cordiali saluti / Freundliche Grüße

JORGE BAPTISTA 

Email:  <mailto:info@newstri.com> info@newstri.com

Web:  <http://www.newstri.com/> http://www.newstri.com

 <http://newstri.com/>   <https://www.facebook.com/tel2u/>    <https://twitter.com/tel2u> 

 

De: Gordon Lesti [mailto:notifications@github.com] 
Enviada em: jueves, 15 de octubre de 2015 9:31
Para: GordonLesti/Lesti_Fpc <Lesti_Fpc@noreply.github.com>
Assunto: Re: [Lesti_Fpc] Block name added to dynamic blocks not working (#143)

 

I wouldn't recommend to have dynamic things in cms pages, but I know that it's sometimes the only solution. Please do not forget to add you block also via any layout.xml to the cms_page_view handle in a not visible way.

**Comment by GordonLesti** [comment]
@jotao23 what distribution list? Github is sending you this mail, cause you are watching this repository.

**Comment by jotao23** [comment]
Can you remove our domain @newstri.com, or jotao23 “joao@newstri.com <mailto:joao@newstri.com> ” of your email distribution list?

 

We don’t have Magento, and we don’t want receive your massive emails everyday

 

Cordial Saludo / Best Regards / Cordialment / Cordiali saluti / Freundliche Grüße

JORGE BAPTISTA 

Email:  <mailto:info@newstri.com> info@newstri.com

Web:  <http://www.newstri.com/> http://www.newstri.com

 <http://newstri.com/>   <https://www.facebook.com/tel2u/>    <https://twitter.com/tel2u> 

 

De: Gordon Lesti [mailto:notifications@github.com] 
Enviada em: jueves, 15 de octubre de 2015 9:41
Para: GordonLesti/Lesti_Fpc <Lesti_Fpc@noreply.github.com>
Cc: jotao23 <joao@newstri.com>
Assunto: Re: [Lesti_Fpc] Block name added to dynamic blocks not working (#143)

 

@jotao23 <https://github.com/jotao23>  what distribution list? Github is sending you this mail, cause you are watching this repository.

**Comment by GordonLesti** [comment]
@jotao23 ARE YOU DRUNK? YOU HAVE TO UNWATCH THIS GITHUB REPOSITORY, I CAN NOT DO THAT FOR YOU.

**Comment by Webmasterei** [comment]
LoL Made my day!
