### ISSUE TITLE
Issue with lazy block 'top.links' not rendering

### ISSUE THREAD

**Issue by flashinnl** [GordonLesti/Lesti_Fpc#144]
I have an issue with magento 1.7.0.2 and the latest Lesti FPC. 

The lazy or dynamic block top.links doesn't render when the full page cache is activated. 

How can i debug or try to fix this? 

Thanks!

**Comment by GordonLesti** [comment]
Please make sure that minification is disabled and that `top.links` is only part of lazy or dynamic blocks.

**Comment by SibhiProbytes** [comment]
I am also facing the same issue
