### ISSUE TITLE
Capacity Issues

### ISSUE THREAD

**Issue by jasperf** [GordonLesti/Lesti_Fpc#147]
Trying to install the extension as our site http://goo.gl/R1vX3g  is extremely slow onloading: TTFB 40 seconds. When I add the key and go for installation I get

`The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.`
![screen shot 2015-09-15 at 5 15 22 pm](https://cloud.githubusercontent.com/assets/344138/9878852/7a47e14c-5bcd-11e5-8f7b-13f715dd5bba.png)
Do you have a capacity issue or is that us?

**Comment by jasperf** [comment]
Never mind. It ran now.

**Comment by jasperf** [comment]
It did run but I get an error now: Fatal error: Call to a member function addMessages() on boolean in /home/user/prelaunch.domain.com/includes/src/__default.php on line 14328

**Comment by GordonLesti** [comment]
please update/disable Magento compiler

**Comment by GordonLesti** [comment]
@jasperf any open questions?

**Comment by jasperf** [comment]
No the issue was resolved this way. Now I was able to reactivate the extension. Just need to work on configuring it now. Thanks again Gordon!
