### ISSUE TITLE
Is that support Dedicated server or not.

### ISSUE THREAD

**Issue by rajatcompubrain** [GordonLesti/Lesti_Fpc#149]
Hi,
Thank you for this extension.
I have install it in my demo store and its working fine.
But when i am installing it in my live store then its going to stop working my store.
My live shop installed on dedicated server(VHM).
I want to know Lesti_fpc support dedicated server or not.
Please revert me.

**Comment by GordonLesti** [comment]
Sorry, I did not understand the question. Why shouldn't it work on a dedicated server?

**Comment by rajatcompubrain** [comment]
I cant understand.
After installation of extension site is showing blank page. 
Even backend is not openig.
Is that required any PHP extension to work it.
Because i have newly buy my server.

**Comment by GordonLesti** [comment]
White blank page means pretty often, that you have an server error. Please take a look your webserver error log. (A very often detected mistake of people that install FPC is, that they did not disable/refresh Magento compiler)

**Comment by rajatcompubrain** [comment]
Hi,
Please check this link.
http://prntscr.com/8j7432 
I have getting this error on the category page

**Comment by GordonLesti** [comment]
@rajatcompubrain can you close the issue?
Your other issue: Did you have a ajax based fitler navigation? If yes, I guess this post can help you https://gordonlesti.com/lestifpc-and-layered-navigation/
