### ISSUE TITLE
Strange behabiour of dynamic block

### ISSUE THREAD

**Issue by Webmasterei** [GordonLesti/Lesti_Fpc#150]
Hi,
I have a problem with cart.sidebar. 

I added it to the dynamic block section. 

If I add something to the cart, I get the new content.
If I reload the page, it turns to the former content. 
If I reload the page another time, the new conent is in again. 

Do you have any idea what this behaviour comes from?

**Comment by GordonLesti** [comment]
Did you remove the block from the lazy ones?

**Comment by Webmasterei** [comment]
That was it. Thanks!
