### ISSUE TITLE
List of cached pages

### ISSUE THREAD

**Issue by oneeleckenobi** [GordonLesti/Lesti_Fpc#157]
Hello,
We use FPC and it's a very helpful extension.
I'am looking a way to crawl urls to precache the site but not urls already in cache to preserve the server.
Did you know how I could find the list of the page in the cache?
Thank you in advance for your help

**Comment by GordonLesti** [comment]
Hello,
I'm sorry, that is not so easy. But if you want to, you can use the event `fpc_save_data_before` to sniff all requested uris on your own.
