### ISSUE TITLE
Rename Age header

### ISSUE THREAD

**Issue by it-can** [GordonLesti/Lesti_Fpc#158]
Please rename the age header in file ```app/code/community/Lesti/Fpc/Model/Observer.php```

Line 75: ```->setHeader('Age', time() - $time);```  to ```->setHeader('X-FPC-Age', time() - $time);```

Line 87: ```Mage::app()->getResponse()->setHeader('Age', 0);```  to ```Mage::app()->getResponse()->setHeader('X-FPC-Age', 0);```

Or make it configurable... Thanks!

**Comment by GordonLesti** [comment]
In general I see no problem with `Age`, I guess it respects the  [W3C Header Field Definitions](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html). Is there a valid reason to change this? You can also disable the `Age`, it's just to test after installation if the cache really works.
