### ISSUE TITLE
PHP Versions

### ISSUE THREAD

**Issue by sirlasc** [GordonLesti/Lesti_Fpc#159]
Do you have an update requirements somewhere? We tried to update to the newest version but did not work due to PHP version. We would love to know what is the earliest version we can use.

**Comment by GordonLesti** [comment]
Why didn't it work? How did you update? In general I would say 5.6 >= php >= 5.3, but I let Travis only test against 5.4 & 5.5, cause that are the current requirements of Magento.

**Comment by sirlasc** [comment]
We update from Magento Connect. We are at Magento versión 1.9.0.1. We wasn`t able to update, we got a mantaince flag.

**Comment by GordonLesti** [comment]
In general I would recommend you to use [modman](https://github.com/colinmollenhour/modman) to install updates and not Magento connect. The php version requirement of the magento connect package is 5.7 >= php >= 5.4 (I know 5.7 will never appear).
