### ISSUE TITLE
Admin Panel issue

### ISSUE THREAD

**Issue by tufanayd** [GordonLesti/Lesti_Fpc#161]
Hi,

In google Chrome when we are working in the admin panel after certain time it logs out and can not login again.

This has started after we install the lesti fpc.

how can I prevent this ?

thanks

**Comment by Webmasterei** [comment]
That is a core feature of magento. Try to improve the session time.

**Comment by Webmasterei** [comment]
The backend is not cached by lesti fpc so no way  it comes from there.

**Comment by GordonLesti** [comment]
Hello @tufanayd 
I'm sorry, but as @Webmasterei already mentioned, It's impossible for Fpc to effect the backend.

Best Regards
Gordon
