### ISSUE TITLE
Minicart block isn't updated after user deletes/updates cart via ajax action

### ISSUE THREAD

**Issue by mat-b-** [GordonLesti/Lesti_Fpc#162]
Magento 1.9.2.2

To reproduce:
1. Add some product to cart
2. Go to home page so it gets cached
3. Go to other page
4. Open minicart at the top, delete the product
5. Go to home page again

Result:
Minicart displays the product still in minicart

Desired result:
Minicart is updated.

Tried adding both minicart_head and minicart_content to dynamic_blocks, but problem is still there.

How can minicart be updated on ajax actions (both product update and delete)?
Or if this can't be done, how can minicart be loaded dynamically?

The following events were added as per #58:
checkout_cart_updateItemOptions,
checkout_cart_ajaxDelete,
checkout_cart_ajaxUpdate

**Comment by GordonLesti** [comment]
@mat-b- How can I reproduce if a ajax cart isn't default in Magento?

**Comment by mat-b-** [comment]
@GordonLesti, please change theme to rwd.

It is included by default from 1.9: http://devdocs.magento.com/guides/m1x/ce19-ee114/RWD_dev-guide.html

Screenshot:
http://i.imgur.com/t4ApYG2.png

**Comment by GordonLesti** [comment]
@mat-b- thank you for the hint, I have reproduced the behavior and will think about a solution.

**Comment by GordonLesti** [comment]
@mat-b- I have added `checkout_cart_ajaxDelete`, `checkout_cart_ajaxUpdate` and `checkout_cart_updateItemOptions` to the `Refresh Actions` and now the ajax cart seems to work fine. https://github.com/GordonLesti/Lesti_Fpc/commit/1779cea22dc4edbed983f9880571aa122b16bdbb

**Comment by mat-b-** [comment]
@GordonLesti it seems that there are still problems.

I have created 1-minute video that shows it: https://youtu.be/vWT9F6Aiz1Y

After item is deleted from minicart, it is shown on some pages (but cart is empty).
Trying to update item's quantity results in an error "Can not save item" (because the item is already deleted).

Only FPC cache is enabled:
![Admin panel](http://i.imgur.com/X2CMq6t.png)

All this was recorded on fresh incognito browser session.

**Comment by GordonLesti** [comment]
I did took a look at the video, but I can't reproduce the the same as in 0:28 were magically the item occurs in the cart again. (I have also disabled all caches expect Fpc).
Sorry if I ask it, but did you made sure that `checkout_cart_ajaxDelete`, `checkout_cart_ajaxUpdate` and `checkout_cart_updateItemOptions` are now in the `Refresh Actions` of the Fpc configs?
If you want to bypass this issue quickly, you can move the block name from lazy to dynamic blocks.

**Comment by mat-b-** [comment]
Yes I did, also moved minicart_head & cart_sidebar to dynamic blocks, still the same
[config.xml.txt](https://github.com/GordonLesti/Lesti_Fpc/files/43872/config.xml.txt)

Live URL is: www.doman.com.pl

I'm puzzled :(

**Comment by GordonLesti** [comment]
@mat-b- can you contact me via email and I will try to solve it if you can give access.

**Comment by mat-b-** [comment]
Sent email, thank you!

**Comment by jarjar123** [comment]
I can reproduce too. Magento 1.9.1.0 RWD.
Same setup. Same result as showed in the video.

**Comment by mat-b-** [comment]
@jarjar123 Make sure to update Config - System - Lesti FPC section. Changes made in config.xml are not enough.

**Comment by danielc1234** [comment]
@mat-b- 
Can you give me exact details how you resolved this issue? I have 1.9.2 RWD theme and having the exact same thing.

This is what I have in there so far....

Dynamic Blocks:
messages,
global_messages,
global_notices,
right.reports.product.viewed,
catalog.inline.layer,
top.links.cart,
mini.cart.top,
onestepcheckout.daskboard,
cart_minicart,
minicart_head,
cart_sidebar

Refresh Actions:
checkout_cart,
checkout_cart_add,
checkout_cart_delete,
checkout_cart_updatePost,
catalog_product_compare_add,
catalog_product_compare_clear,
catalog_product_compare_remove,
wishlist_index_add,
wishlist_index_remove,
wishlist_index_update,
wishlist_index_allcart,
wishlist_index_configure,
checkout_onepage_success,
checkout_onepage,
mirasvit_searchIndex_block_results,
checkout_cart_updateItemOptions,
checkout_cart_ajaxDelete,
checkout_cart_ajaxUpdate,
minicart_head,
cart_minicart

**Comment by mat-b-** [comment]
@danielc1234 That should work, are you sure you entered this in the right place?

**Comment by danielc1234** [comment]
I think I got it working now. Our server has redis cache that needed to be cleared on the server level. Just clearing all of magento cache was not enough.

**Comment by JethvaVipul** [comment]
Hello All,
Having same issue on my site. Header cart item is not update when I am in product detail page but when I go to checkout then header cart item is update. Can you please guide me how I fix this issue. Magento ver.1.9.2.2.

**Comment by mlabate** [comment]
Hi, I'm figuring out the same issue on Magento 1.9.2.4.
There's something new about this issue?

**Comment by redwolfweb** [comment]
Hello,
I've the same problem with sns kalolia theme minicart, well it's also worst than what is described here, the cart remains cached for all people that enter on the same page. So, if I add 1 product to the cart, and the cache being cleaned when my cart have 1 product, any pages that the user have visited after the cache clean becomes visible with him product in the minicart for all users!
Any help would be greatly appreciated! Thanks.
