### ISSUE TITLE
Issue with not updating header cart

### ISSUE THREAD

**Issue by harshilpatwa** [GordonLesti/Lesti_Fpc#163]
I have installed Lesti_FPC and facing issue with not updating header cart.
When I do add to cart from category page , it not update the items in top mini cart (not used Ajax cart)
same issue with Product page.
If I refresh few times or refresh the cache then it shows. 
Also same happening with Home page - if the product shows on category page add to cart then it not showing at all in Front-end.

**Comment by GordonLesti** [comment]
Hello @harshilpatwa 
you are sure that you have the right block name?

**Comment by harshilpatwa** [comment]
Hello yes I am sure having right block name.

See this is site.

http://test.diydoctor.bathcomms.com


Thanks & Regards,
Harshil Patwa
Php Web Developer ( Magento Developer)
Elsner Technologies Pvt. Ltd.

**Comment by harshilpatwa** [comment]
How can I bypass the header cart ?

**Comment by GordonLesti** [comment]
Please contact me via email and I will try to solve that issue if you give me access?

**Comment by harshilpatwa** [comment]
Can you give me emai id please.

**Comment by GordonLesti** [comment]
info@gordonlesti.com

**Comment by harshilpatwa** [comment]
I see this is not fixed.

**Comment by GordonLesti** [comment]
Hello @harshilpatwa 
I will take a look at it as soon as possible, but in my eyes it's not an public issue anymore.

**Comment by harshilpatwa** [comment]
Hello Gordon,
Well the good news is I have fixed the issue.

**Comment by hetulkothari** [comment]
@harshilpatwa - how did you manage to do this? I am having a similar issue with my site... Unable to get the mini ajax cart updated on my website header
