### ISSUE TITLE
Issue with not updating header cart

### ISSUE THREAD

**Issue by harshilpatwa** [GordonLesti/Lesti_Fpc#166]
I have installed Lesti_FPC and facing issue with not updating header cart.
When I do add to cart from category page , it not update the items in top mini cart (not used Ajax cart)
same issue with Product page.
If I refresh few times or refresh the cache then it shows.
Also same happening with Home page - if the product shows on category page add to cart then it not showing at all in Front-end.

**Comment by GordonLesti** [comment]
https://github.com/GordonLesti/Lesti_Fpc/issues/163
