### ISSUE TITLE
How to calculate the lifetime?

### ISSUE THREAD

**Issue by jarjar123** [GordonLesti/Lesti_Fpc#167]
Hi. I have many doubts about _lifetime_.

* May I face any issues setting up a monthly or annual _lifetime_?
* What problems could we face? If so, what events were missed?
* How much time is good for a wide catalog?

    e.g. I have 1k products and 1k views per day
    Roughly speaking 24 hours means a very low hit rate
    In order to illustrate I will apply something like below:
    * 100 - 100 x Products / (Views x Days) = Hit Rating
    * 100 - 100 x 1 / (1 x 1) = 0% (1 product / 1 view means zero hits)
    * 100 - 100 x 1 / (10 x 1) = 90% (1 product / 10 views means 9 hits)

    Real example:
    * Products: 2722
    * Views: 16170
    * Lifetime: 1 day
    * 100 - 100 x 2722 / (16170 x 1) = 83%

    So if I want at least 90% of hit rating I should improve the _lifetime_ for more views.
    * 100 - 100 x 2722 / (16170 x 2) = 92%

    PS. I'm not forgetting the other front pages like _Categories, CMS, products/page_. This is just an example.

* Is this important? Am I crazy?

**Comment by GordonLesti** [comment]
Hello @jarjar123 you can edit the lifetime if you want to without any problems. 24 hours is just default. Your calculation makes sense.
