### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by sirlasc** [GordonLesti/Lesti_Fpc#168]
When updating from Magento Connect I get an error that PHP version upgrade is needed. We are currently on :   

PHP 5.4.45 (cli) (built: Oct 16 2015 11:24:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

Should we install it from where?

**Comment by GordonLesti** [comment]
Hello @sirlasc 
Really?
The min version for the current Magento Connect package is 5.4.0 and the max version is 5.7.0 (I know funny). So normally that should work.
But by the way, I would recommend to you to install 5.5 cause 5.4 has no security support anymore from PHP.
For installation in general I would always recommend using manual install, or much better modman, or the best way in my eyes with composer. Magento Connect is always a little bit painful.
Please close the ticket if that ansers your question.
