### ISSUE TITLE
Will Extension work with PHP7?

### ISSUE THREAD

**Issue by danielc1234** [GordonLesti/Lesti_Fpc#169]
Hi,

Wondering if your extension will work with PHP7?

And do you plan on having one for Magento 2.0?

Thanks!
Dan

**Comment by GordonLesti** [comment]
Hello @danielc1234 
I didn't tested on my own, but I would guess it should work with PHP7. The better question at the moment is, if Magento works with PHP7?
No, I won't plan a Magento 2.0 extension, Magento 2.0 has it's own fullpagecache and that works pretty good in my eyes.

Best Regards
Gordon

**Comment by durzel** [comment]
Hi Gordon, the module doesn't install on PHP7, at least not the currently available Magento Connect version (1.4.2), because it has a "max" PHP version of 5.7.0.

**Comment by danielc1234** [comment]
@durzel Grab the raw code and copy it over via ftp, etc.
I have it working with PHP7 on our local server.

**Comment by durzel** [comment]
Yeah, I will do, just quite like having stuff installed and updated through Magento Connect (I'm aware it's behind the current version - 1.4.4?). Thanks :)

**Comment by Webmasterei** [comment]
Does Magento 1.9.2.2 work at all on PHP7?

**Comment by durzel** [comment]
Yes, 1.9.2.2 works on PHP7, but not out of the box - some minor core changes are required.  I'm using https://github.com/Inchoo/Inchoo_PHP7 which has had some development works for me.
