### ISSUE TITLE
header mini cart not updating

### ISSUE THREAD

**Issue by livilajed** [GordonLesti/Lesti_Fpc#170]
header mini cart updated when add or remove product, but when refresh page show Previous state before add/delete product.
I've added mini cart block name in the Lazy Blocks and Dynamic Blocks configurations.

**Comment by GordonLesti** [comment]
Hello @livilajed 
please put a block only to lazy or dynamic. If you have an ajax based add to cart button better use dynamic blocks. Here again a post that explains the behavior https://gordonlesti.com/what-are-lazy-and-dynamic-blocks-in-lestifpc/
