### ISSUE TITLE
Layered Navigation problem

### ISSUE THREAD

**Issue by livilajed** [GordonLesti/Lesti_Fpc#171]
I am using ajax for Layered Navigation
I can only select or clear a filter for the first time and after do it, layered navigation with those filters, not work.

**Comment by GordonLesti** [comment]
Hello @livilajed 
in the most cases a ajax based navigation needs some `Uri Params`. Here is a post about it https://gordonlesti.com/what-are-uri-params-in-lestifpc/

**Comment by livilajed** [comment]
Hi
would you please tell me what Uri Param need for this link 
http://demo.magentech.com/themes/sm_market/mobiles.html

**Comment by GordonLesti** [comment]
`isLayerAjax=/^1$/`

**Comment by doctea** [comment]
adding is_ajax to the uri_params configuration hasn't seemed to solve this problem for the Amasty_Shopby (Improved Layered Navigation) for me; adding this line before the final 'return true;' line of function canCacheRequest() has seemed to solve it for me though:-

        if (!is_null($request->getParam("is_ajax"))) return false;      // line added by Tristan3dtotal for 'Still weirdness' http://devwiki.3dtotal.com/project:shop_upgrade:ultimo:theme:layered_navigation_filter_rating_wrong_version_cached#still_weirdness 2016-11-11 ...

**Comment by GordonLesti** [comment]
@doctea I guess adding `is_ajax=/^1$/` to Miss Uri Params has the same effect as your line.

**Comment by doctea** [comment]
@GordonLesti I thought that should work too -- however I've just tested it and it doesn't seem to work for me!

**Comment by GordonLesti** [comment]
@doctea did you have cleaned Magento config cache and FPC after setting `Miss Uri Params`?

**Comment by doctea** [comment]
@GordonLesti Yep, unless my method of cache-clearing isn't working somehow -- but I've done a 'flushall' from redis-cli etc, and other configuration settings seem to be getting updated as expected.  

I added logging to the canCacheRequest method and $request->getParam("is_ajax") does return "1" for ajax requests and null ('') otherwise, so the regex looks fine to me too..
