### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by dleone81** [GordonLesti/Lesti_Fpc#176]
I've an issue on my staging environment ...
I've Magento installation multi-store configured.

First store > b2b > has Vinai's module installed ad active:
https://github.com/Vinai/loginonlycatalog

Second store > b2c has core login

I'm unable to access on b2b store

**Comment by GordonLesti** [comment]
Hello @dleone81 
please enable `Customer Groups` in the configs of Fpc and it should work.
