### ISSUE TITLE
How to refresh lesti fpc cache from command line?

### ISSUE THREAD

**Issue by JohanDH** [GordonLesti/Lesti_Fpc#181]
Hi,

I want to use a cachewarmer script I found on stackoverflow. http://stackoverflow.com/questions/31181640/magento-fpc-cache-warm-with-user-groups-wget-lesti-fpc
How can I first refresh the lestifpc cache from the command line?

#!/bin/bash
wget --quiet http://YOUR-URL.co.uk/sitemap.xml --output-document - | egrep -o "http://YOUR-URL.co.uk/[^<]+" | wget -q --delete-after -i -

**Comment by pschoenmakers** [comment]
You can do a: 
`redis-cli -n #num# flushdb`

replace #num# with your actual database number setup in /app/etc/fpc.xml

**Comment by GordonLesti** [comment]
This is one solution https://github.com/GordonLesti/Lesti_Fpc/issues/198#issuecomment-199681938

**Comment by webzellentOpenSource** [comment]
Here are two helpful links:

[http://stackoverflow.com/questions/30842912/how-to-refresh-full-page-cache-of-a-particular-product-in-magento](http://stackoverflow.com/questions/30842912/how-to-refresh-full-page-cache-of-a-particular-product-in-magento)

[http://stackoverflow.com/questions/30863780/magento-specific-product-clean-cache-using-lesti-fpc-when-i-change-stock-in-th](http://stackoverflow.com/questions/30863780/magento-specific-product-clean-cache-using-lesti-fpc-when-i-change-stock-in-th)
