### ISSUE TITLE
reports.product.viewed only updating after page reload

### ISSUE THREAD

**Issue by Webmasterei** [GordonLesti/Lesti_Fpc#182]
Hi Gordon,
I have a block reports.product.viewed (same as right.reports.product.viewed).
I added it to the dynamic blocks. 
On first click on a page, it does not load. If I reload by cmd+r it shows. 

Do you have any thoughts on this?

Regards

Bernhard

**Comment by GordonLesti** [comment]
Hello @Webmasterei 
a typical reason can be, that the block is in dynamic and lazy blocks. Please make sure that the name is only in dynamic or lazy, not both. An other typical reason can be, that the block name is not unique in the layout.

**Comment by Webmasterei** [comment]
Dynamic blocks are:

messages,
global_messages,
global_notices,
global_cookie_notice,
reports.product.viewed,
right.reports.product.viewed

Lazy Blocks are:
top.links,
catalog.compare.sidebar,
wishlist_sidebar,
welcome,
minicart_head,
right.poll,
cart_sidebar

Issue is the same in local as in stage.

**Comment by Webmasterei** [comment]
Now it works for no (to me) obvious reason.

**Comment by Webmasterei** [comment]
It's not over! 

Firstly it was due to setLCacheLifetime for blocks things I could get rid of. 
Secondly I renamed it to right. right.reports.product.viewed and now it works on the first call.

The only thing left is, that the first call of the block contains the parameter __SID=U. If I reload the page, this is gone too. Do you have an answer for that?

**Comment by GordonLesti** [comment]
should I reopen the issue?

**Comment by Webmasterei** [comment]
...though I did not change a thing today it is gone. Leave it closed as I will stop wondering... and start beeing content about it.
