### ISSUE TITLE
Issue with CMS Static Blocks & Category Descriptions

### ISSUE THREAD

**Issue by danielc1234** [GordonLesti/Lesti_Fpc#185]
We are having a strange thing happen on our category pages. We have a category(A), with a single column page with a cms block. And another category(B) page with 2-columns and using description with no CMS static block. When Lesti is on category(A)'s cms static block disappears and category(B) shows the proper category description, but adds the CMS static block of category(A) below the description's text. 

Any idea on what might be doing this at all? I have been pulling my hair out for days trying to figure it out.

Thanks Dan

**Comment by GordonLesti** [comment]
Hello @danielc1234 
sounds like a very special problem, can you contact me via email (info[at]gordonlesti.com) and hopefully we find a solution for your problem.
