### ISSUE TITLE
How to exclude from caching the price in the category of goods imposed by CMS.

### ISSUE THREAD

**Issue by myZmage** [GordonLesti/Lesti_Fpc#186]
Hello Gordon. Please help me I insert product category on the home page through the CMS.
`{{Block type="catalog/product_list"template="catalog/product/list.phtml"category_id="1"}} `
I need to exclude from caching the price of goods.
I added to the Dynamic Blocks - catalog_product_price_template, but it does not work for CMS pages.

Tell me how can I eliminate from the cache in the price derived in this way categories.
thank

**Comment by GordonLesti** [comment]
Hello @myZmage 
this isn't that easy.
* Give the cms block a name in layout, for example `category.one`: `{{Block type="catalog/product_list" template="catalog/product/list.phtml" name_in_layout="category.one" category_id="1"}}`
* Add a not visible block to this handle with the same attributes in the responsible layout.xml, for example `local.xml`:
```
<block type="catalog/product_list" template="catalog/product/list.phtml" name="category.one">
    <action method="setCategoryId"><category_id>1</category_id></action>
</block>
```
* Add the block `category.one` to the dynamic blocks.

Please note in general, I wouldn't recommend this way.
Can you explain why you need to exclude the prices from caching?

**Comment by myZmage** [comment]
Thanks for the reply all happened.
Dynamic price is loaded with XML requests from other resources and can, in the case of the cache, do not correspond to reality.
