### ISSUE TITLE
Lifetime FPC

### ISSUE THREAD

**Issue by tomutassc** [GordonLesti/Lesti_Fpc#188]
I want to know for a magento site...how can i modify the FPC lifetime from 86400 which is 24 hours to never (clear cache manually) or to 30 days for example.
please explain to me step by step  as i know nothing about magento ( i have access to ftp and to database)
in what folder the cache files are stored?

**Comment by GordonLesti** [comment]
Hello @tomutassc 
you can set a general lifetime in the file `app/etc/fpc.xml`, the file `app/etc/fpc.xml.sample` will help you with the schema. If you have filecache as backend, Fpc will store the cache at the same position as magento, but with the prefix `fpc`. I guess the default postion for magento cache is `var/cache`.
