### ISSUE TITLE
Store View not sticking

### ISSUE THREAD

**Issue by apdiving** [GordonLesti/Lesti_Fpc#192]
Hello,

Installed everything fine. I notice a definite decrease in load time which is great.

However when I change store language and browse to another page, the store view switches back to default. Any ideas? 

http://www.apdiving.com/shop/bcd-open-circuit.html

Switcher is top left. Change language and then browse further into a category

**Comment by GordonLesti** [comment]
Hello @apdiving 
If I change to german for example a click around in the menu or the products, everything stays germen. Sorry, but I can't reproduce this problem.

**Comment by apdiving** [comment]
Apologies this seems to be due to my locally saved cookies. Probably a conflict somewhere...
