### ISSUE TITLE
Refresh FPC in magento admin panel didn't work

### ISSUE THREAD

**Issue by tttungs** [GordonLesti/Lesti_Fpc#194]
Hi there, 
After install  the page load is good , I want refresh fpc in admin panel magento but it didn't work , I have to remove these files manually (log in ssh/ftp) , seem these file (var/cache/fpc../...)auto create with permission folder is 777 and file is 600.

Is there have any file which i can edit this to re-create with file permission is 644 ? 
Best regard,

**Comment by GordonLesti** [comment]
Hello @tttungs 
folder permission 777 is set here [Lesti_Fpc_Model_Fpc](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Model/Fpc.php#L29). This is the same as in [Mage_Core_Model_Cache](https://github.com/OpenMage/magento-mirror/blob/1.9.2.4/app/code/core/Mage/Core/Model/Cache.php#L79). I guess you can change that value with `app/etc/fpc.xml`. The file permissions are set by [Mage_Cache_Backend_File](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Model/Fpc.php#L29), the same as Magento default caches. But I think you can change this also via `app/etc/fpc.xml`.

But I guess you should change that. `600` is the recommended file permission for caches, cause only the webserver user should build and clean those files. Are you sure that refreshing in admin panel didn't work?

**Comment by tttungs** [comment]
Yes thanks for your advise , i can understand the risk if i change that permission.
I will recheck system again.

Thank you
