### ISSUE TITLE
Caching of search Pages

### ISSUE THREAD

**Issue by Nierjesh** [GordonLesti/Lesti_Fpc#197]
Hi I have created one custom page so I just want to create the cache of that page.When I am looking into the result in monitor command then I got custom page request is made but no cache is generated.

I also want to create the cache of catalogsearch pages so please suggest me what I have to do for that.
in cacheable action I have defined "catalogsearch_result_index" but still cache is not generated for that.

**Comment by GordonLesti** [comment]
Hello @Nierjesh 
caching of search results works fine for me if I add `catalogsearch_result_index` to the `Cachable actions`.
```
cms_index_index,
cms_page_view,
catalog_product_view,
catalog_category_view,
catalogsearch_result_index
```
But that would show always the same search result. So I need to add `q` to the `Uri Params`.
```
id,
category,
cat,
page_id,
p,
limit,
dir,
order,
mode,
q
```

**Comment by Nierjesh** [comment]
Hi Gorden:

below is my setting:
Cacheable actions:
cms_index_index,
cms_page_view,
catalog_product_view,
catalog_category_view,
catalogsearch_result_index

Dynamic Blocks:
messages,
global_messages,
global_notices,
cart_sidebar,
right.reports.product.viewed,

Refresh Actions:

checkout_cart_add,
checkout_cart_delete,
checkout_cart_updatePost,
catalog_product_compare_add,
catalog_product_compare_clear,
catalog_product_compare_remove,
wishlist_index_add,
wishlist_index_remove,
wishlist_index_update,
wishlist_index_allcart,
wishlist_index_configure,
checkout_onepage_success,
poll_vote_add

Lazy Blocks:
top.links,
catalog.compare.sidebar,
wishlist_sidebar,
welcome,
minicart_head,
right.poll

URI Params:

id,
category,
page_id,
p,
limit,
dir,
order,
mode,
/^[a-z]*[A-Z]*/,
q

Miss URI Params:
no_cache=/^1$/,
limit=/^([0-9]+)|(all)$/,
dir=/^[0-9a-z_]+$/,
order=/^[0-9a-z_]+$/,
mode=/^[0-9a-z_]+$/,
___store=/^[a-z]{1}[0-9a-z_]*$/

Category Session Params:

limit_page,
sort_order,
sort_direction,
display_mode


When I search "morse drum" on my site then it opens catalogsearch page."Morse Drum" belongs to our Manufacturer also so I redirect raptorsupplies.com/catalogsearch/result/?q=morse+drum to  raptorsupplies.com/morse-drum ,Now Please let me know where I am wrong.

Thanks in advance.

**Comment by Nierjesh** [comment]
Hi Gorden,

Please help.we are facing a lot of issue due to this.

**Comment by GordonLesti** [comment]
Hello @Nierjesh 
can you please check at this line (Lesti_Fpc_Model_Observer::httpResponseSendBefore)[https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Model/Observer.php#L104] the value of the variable `$fullActionName` if you are on the search result page?
Why did you have this `/^[a-z][A-Z]/` in the `Uri Params`?

By the way, my name is Gordon:)

**Comment by Nierjesh** [comment]
Hi Gordon,

Thanks for your reply.
I got that action name is "searchlandingpage_page_view" when I inserted this then it started to cache the page but it is not changing after applying the fiter.
Same for brand page:
action name is "catalogsearch_term_brand" but it is not chaning when we click on a,b,c or any other alphabet .Alphabet is working just as search.

**Comment by Nierjesh** [comment]
Hi Gordon,

For brand pages problem is solved.but for "searchlandingpage_page_view" probelm is still there original page https://staging.raptorsupplies.com/icm has been cached but when we are applying filter like "https://staging.raptorsupplies.com/icm?item=492493" then it is displaying same result which was in 
https://staging.raptorsupplies.com/icm ,here item is one attribute on which filter is applied like this there are several attribute so I can not define all attribute in URI_PARAMS .Please help me.

**Comment by GordonLesti** [comment]
Is `searchlandingpage_page_view` Magento default? If not, maybe the event [fpc_helper_collect_params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Helper/Data.php#L107) can help you.

**Comment by Nierjesh** [comment]
Hi Gordon,

problem is resolved .I just added  /[a-zA-Z]/ in the Uri Params.so now it is working fine.
