### ISSUE TITLE
Dynamic Block keeps cache

### ISSUE THREAD

**Issue by ericho09** [GordonLesti/Lesti_Fpc#200]
I have a static block (http://prntscr.com/aiksob) is a dynamic block. 
Block name is "Sub_cat_dont_touch"

I added "Sub_cat_dont_touch" to dynamic blocks in FPC setting (http://prntscr.com/aikrij), but it doesn't work and keep cache. It always remember the first category I clicked (http://prntscr.com/aikvpg).

Can you help? and let me know if I did it wrong.

**Comment by GordonLesti** [comment]
`Mage_Cms_Block_Block` are cached by Magentos Block Cache.
