### ISSUE TITLE
Issue with Lesti_Fpc

### ISSUE THREAD

**Issue by theevilapplepie** [GordonLesti/Lesti_Fpc#201]
Running Magento Community Version 1.9.0, When installing manually we get this when the module is enabled:

2016-03-27T07:03:58+00:00 ERR (3):
exception 'Mage_Core_Exception' with message 'Invalid block type: Lesti_Fpc_Core_Block_Messages' in /data/appdir/app/Mage.php:595
Stack trace:
#0 /data/appdir/includes/src/__default.php(38340): Mage::throwException('Invalid block t...')
#1 /data/appdir/includes/src/__default.php(38282): Mage_Core_Model_Layout->_getBlockInstance('core/messages', Array)
#2 /data/appdir/includes/src/__default.php(38418): Mage_Core_Model_Layout->createBlock('core/messages', 'messages')
#3 /data/appdir/includes/src/__default.php(24374): Mage_Core_Model_Layout->getMessagesBlock()
#4 /data/appdir/includes/src/Mage_Adminhtml_Controller_Action.php(276): Mage_Core_Controller_Varien_Action->_initLayoutMessages('adminhtml/sessi...')
#5 /data/appdir/app/code/core/Mage/Adminhtml/controllers/IndexController.php(81): Mage_Adminhtml_Controller_Action->loadLayout()
#6 /data/appdir/includes/src/__default.php(24149): Mage_Adminhtml_IndexController->loginAction()
#7 /data/appdir/includes/src/__default.php(28574): Mage_Core_Controller_Varien_Action->dispatch('login')
#8 /data/appdir/includes/src/__default.php(28104): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /data/appdir/includes/src/__default.php(30969): Mage_Core_Controller_Varien_Front->dispatch()
#10 /data/appdir/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /data/appdir/index.php(102): Mage::run('', 'store')
#12 {main}

Reviewing, I'm not sure why this is happening as everything configured looks proper.
This occurs with or without the configuration xml as long as the module is enabled.

**Comment by GordonLesti** [comment]
Please refresh or disable Magento Compiler & make sure class exists.

**Comment by theevilapplepie** [comment]
Ahhhhhh :( I knew it was something stupid, but I didn't know what.
I appreciate the follow up!
