### ISSUE TITLE
No caching

### ISSUE THREAD

**Issue by octaviancernat** [GordonLesti/Lesti_Fpc#202]
Hello,

I'm new to FPC.
Is there any known issue regarding the use of a SSL certificate? I'm using FPC on magento 1.9.2.4 and it worked fine when installed.
Since I've installed the SSL certificate,  FPC doesn't seem to work anymore. I was using it with Redis (fpc.xml), when noticed the slow load. 
I've put it on file system but it doesn't write any files.
I've put magento cache and session to file system works ok.

Error logs don't give any clue about this issue. Any help would be appreciated.

**Comment by GordonLesti** [comment]
Hello @octaviancernat 
no, there is no known issue with SSL. The type of cache backend or session storage isn't important as long it works. The function [Lesti_Fpc_Model_Observer::controllerActionLayoutGenerateBlocksBefore](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Model/Observer.php#L33) is always a good point to start debugging.
