### ISSUE TITLE
Delete any page Cache based on specific URL

### ISSUE THREAD

**Issue by Nierjesh** [GordonLesti/Lesti_Fpc#203]
I want to delete the cache based on url .When I search I found there is option to flush the cache based on product id or category id but I want to delete the cache of that pages which do not belongs to product or category like home page,manufacturer pages.So i am struggling to delete the cache of specific URL.

**Comment by GordonLesti** [comment]
Hello @Nierjesh 
deleting by uri isn't possible, cause the cache is build so that `http://example.com/catalog/product/5/` and `http://example.com/product5name.html` are the same cache items. You can clean special cms pages with `Mage::getSingleton('fpc/fpc')->clean(array(sha1('cms_' . $pageId)));` or all cms pages with `Mage::getSingleton('fpc/fpc')->clean(array(sha1('cms_')));`. I hope this will help you.

**Comment by Nierjesh** [comment]
Thanks a lot.Gordon.
Let me try it then will update you accordingly.

On Wed, Mar 30, 2016 at 7:40 PM, Gordon Lesti <notifications@github.com>
wrote:

> Closed #203 <https://github.com/GordonLesti/Lesti_Fpc/issues/203>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GordonLesti/Lesti_Fpc/issues/203#event-608319663>
>



-- 

*Best Regards,*

*Nierjesh Kumar*

[image: NG TC Final VS]

*NextGen eSolutions (P) Ltd.*

*A-8, Mohan Co-operative Industrial Estate,*

*Mathura Road, New Delhi, INDIA - 110044*

*M: 09560055196*

*T: 91-11-30810200*

*F: 91-11-26950011*
*www.nextgenesolutions.com <http://www.nextgenesolutions.com/>*



*Please do not print this email unless it is absolutely necessary. *

DISCLAIMER

The information contained in this electronic message and any attachments to
this message are intended for the exclusive use of the addressee(s) and may
contain proprietary, confidential or privileged information. If you are not
the intended recipient, you should not disseminate, distribute or copy this
e-mail. Please notify the sender immediately and destroy all copies of this
message and any attachments.

*WARNING:* Computer viruses can be transmitted via email. The recipient
should check this email and any attachments for the presence of viruses.
The company accepts no liability for any damage caused by any virus
transmitted by this email.
