### ISSUE TITLE
Mage 1.8.1.0 error Lesti_Fpc 1.4.5

### ISSUE THREAD

**Issue by dleone81** [GordonLesti/Lesti_Fpc#205]
Hi,

After upgrading Lesti_Fpc version I have this error:
Strict Notice: Declaration of Lesti_Fpc_Model_Fpc::save() should be compatible with that of Mage_Core_Model_Cache::save() in /mage/magento/app/code/community/Lesti/Fpc/Model/Fpc.php on line 167

front end is down

Waiting you
D

**Comment by GordonLesti** [comment]
Please downgrade to version of release 1.4.5, not master & I will fix that as soon as possible.

**Comment by GordonLesti** [comment]
I very sorry for this mistake. https://github.com/GordonLesti/Lesti_Fpc/pull/207
