### ISSUE TITLE
Strict Notice: Lesti_Fpc_Model_Fpc::save

### ISSUE THREAD

**Issue by AndreKlang** [GordonLesti/Lesti_Fpc#206]
With development mode on, I get a Strict Notice:

```
Strict Notice: Declaration of Lesti_Fpc_Model_Fpc::save() should be compatible with Mage_Core_Model_Cache::save($data, $id, $tags = Array, $lifeTime = NULL)
```
To suppress it we can just remove `Lesti_Fpc_Model_Fpc_CacheItem` from the argument declaration:
```
public function save(Lesti_Fpc_Model_Fpc_CacheItem $item, $id, $tags=array(), $lifeTime=null)
```

**Comment by GordonLesti** [comment]
Hello @AndreKlang 
would you like to create a PR?

**Comment by GordonLesti** [comment]
@AndreKlang 
thank you, I very sorry for this mistake. https://github.com/GordonLesti/Lesti_Fpc/pull/207
