### ISSUE TITLE
Page Not Updating

### ISSUE THREAD

**Issue by jacobabey1** [GordonLesti/Lesti_Fpc#209]
Kindly help out.
The index page  is not updating to current changes (Mega Menus) on page.

**Comment by GordonLesti** [comment]
Hello @jacobabey1 
a little bit more information would be helpful.

**Comment by jacobabey1** [comment]
Whenever I make changes , relating to the Menus of the website (index page) , and flash the Cache Storage  the effects don't show.
But if I disable the fpc , the new changes take effects. However when I enable the fcp , it reverts to back to old layout.

**Comment by GordonLesti** [comment]
Did you also clean Fpc cache?

**Comment by jacobabey1** [comment]
Dashboard >>System >> Cache Mangement >> Fpc "Full Page Cache" , 
I flashed it .
Hope I got it right ?

**Comment by GordonLesti** [comment]
Yes, that sounds right. Strange, can you check for the `Age` in the response header of your index page after flush? Is it `0` or a value bigger thatn `0`?

**Comment by jacobabey1** [comment]
I have to admit need a little help here , were can I locate the "Age"  to check it , and how to make changes to it.

**Comment by GordonLesti** [comment]
If you enable `Show Age` in the configs of Fpc you should see `Age` in the http response header. That will give you the information how old the cache item is in seconds.

**Comment by jacobabey1** [comment]
Thanks , It's working now. 
I used the FTP to clear the "var/cache" and "var/sessions"
