### ISSUE TITLE
ajax.phtml not valid template

### ISSUE THREAD

**Issue by sholdowa** [GordonLesti/Lesti_Fpc#21]
Hi Gordon,

Have a 1.7.0.2 site running the latest Lesti_Fpc backed by redis/cm_cache_backend_redis. It's raising the error 

2013-08-27T20:55:13+00:00 CRIT (2): Not valid template file:frontend/base/default/template/fpc/catalog/product/view/ajax.phtml

in var/log/system.log.

File is unchanged by us. Should I be worried?

Cheers,

Steve

**Comment by iget-master** [comment]
After SUPEE-9767, the @jonathanvaughn solution doesn't work anymore since theres no `allow symlinks` option anymore.

To solve it I used the first answer on [this Magento Stackexchange question](https://magento.stackexchange.com/questions/184184/how-to-enable-symlinks-after-supee-9767-v2-install)
