### ISSUE TITLE
Header issue when using API call on HHVM

### ISSUE THREAD

**Issue by Mic2005** [GordonLesti/Lesti_Fpc#210]
Hi Gordon,

When we try to make a API call to our Magento development envirioment we receive some header code from Lesti FPC something like: Strikt Standards, Declaration of Lesti_Fpc_Model_Fpc::

![api](https://cloud.githubusercontent.com/assets/11639487/14430290/43e4013e-0001-11e6-8f4b-cb5f80a2b67e.png)

When we switch Lesti FPC off this text is gone and we can make a connection correctly. Can you explain why we receive this header and how to turn this off or fix this? We get a content length mismatch in the response Header and can't setup this connection. 
We use Magento 1.7.0.2 on Redis Cache and HHVM 

Regards, Micha

**Comment by GordonLesti** [comment]
Hello @Mic2005 
this should be fixed with https://github.com/GordonLesti/Lesti_Fpc/pull/207

**Comment by Mic2005** [comment]
Gordon, thanks you. It works!
