### ISSUE TITLE
PHP7 compatibility Magento 1.9.x

### ISSUE THREAD

**Issue by Insect2015** [GordonLesti/Lesti_Fpc#211]
Hello Gordon,

I see that the exstension not full compatibility is with PHP 7 Magento 1.9.x

I use exstension Inchoo_PHP7 so some of the exstension will be working.

Best regards,
Michel

**Comment by GordonLesti** [comment]
Hello @Insect2015 if you find a not PHP7 compactible part, let me know.

**Comment by Mic2005** [comment]
I run CE 1.7.2.4 on PHP7 for 6 weeks and did not find a issue with Lesti::FPC
Cache everything except productpages

**Comment by GordonLesti** [comment]
Thank you @Mic2005 
I will close the Issue.
