### ISSUE TITLE
Manually Delete Lesti Cache

### ISSUE THREAD

**Issue by apdiving** [GordonLesti/Lesti_Fpc#212]
Is there a way to manually remove all Lesti FPC cache files? I am having an issue where our home page will not update to the new design while Lesti FPC is enabled. I have tried everything to flush and refresh our caches but no change.

**Comment by GordonLesti** [comment]
Hello @apdiving 
if you use Filecache as cache backend, you can remove the cached files with `rm -r var/cache/fpc*`, presupposed that your Magento cache directory is `var/cache`.

**Comment by apdiving** [comment]
Hi, yes we do. I have removed all fpc* folders from this area but still I see an old home page when FPC is switched on. It's very odd as this problem doesn't affect any other part of our website. Just the landing.

**Comment by GordonLesti** [comment]
I have made request to `http://www.apdiving.com/shop/` and this page is in cache since 2147787 seconds or more than 24 days.
Did you have a file `app/etc/fpc.xml`?

**Comment by apdiving** [comment]
How strange, why would it cache for that long? 

Yes it contains: 

```
<config>
    <global>
        <fpc>
            <lifetime>86400</lifetime>
            <backend>memcached</backend>
            <memcached>
                <servers>
                    <server>
                        <host><![CDATA[127.0.0.1]]></host>
                        <port><![CDATA[11211]]></port>
                        <persistent><![CDATA[1]]></persistent>
                    </server>
                </servers>
                <compression><![CDATA[6]]></compression>
                <cache_dir><![CDATA[]]></cache_dir>
                <hashed_directory_level><![CDATA[]]></hashed_directory_level>
                <hashed_directory_umask><![CDATA[]]></hashed_directory_umask>
                <file_name_prefix><![CDATA[]]></file_name_prefix>
            </memcached>
        </fpc>
    </global>
</config>
```

**Comment by GordonLesti** [comment]
Now we know that you are using memcached as cache backend :)

**Comment by apdiving** [comment]
Is this where my problem lies?

**Comment by GordonLesti** [comment]
I guess yes. I would like to help you, but `Lesti_Fpc_Model_Fpc` is just extending from `Mage_Core_Model_Cache` and uses just the Api of this class to flush, clean or save into the cache backend. I guess you have to start debugging why it isn't possible for Fpc to flush the memcached.

**Comment by apdiving** [comment]
I'll keep an eye on that page... No other page was held for that amount of time. And considering it was definitely update since it's lifetime of 24 days, it's odd that the file wasn't flushed.

Thanks for your help with this. Great extension :)
