### ISSUE TITLE
Welcomeblock still cached

### ISSUE THREAD

**Issue by apantaleo** [GordonLesti/Lesti_Fpc#214]
Hello

i have a big problem on welcome-msg block i set 

welcome,
welcome-msg,

both in Lazy and Dynamic Blocks under System -> Configuration

but sometime (randomly) it cache that block and give me Hello NAME SURNAME of another customer.
Can someone help me?

**Comment by GordonLesti** [comment]
Hello @apantaleo 
what version of Magento & Fpc did you run? NEVER but a block into dynamic and lazy, only one.

**Comment by apantaleo** [comment]
Hello @GordonLesti 
Magento ver. 1.9.2.1
FPC ver. 1.4.5

**Comment by GordonLesti** [comment]
I guess you will have custom theme, but can you search for the position of the block in a layout xml file. For example like `<block type="page/html_welcome" name="welcome" as="welcome"/>` in [app/design/frontend/rwd/default/layout/page.xml](https://github.com/OpenMage/magento-mirror/blob/1.9.2.1/app/design/frontend/rwd/default/layout/page.xml#L105) and for a call of the block in a template file like `<p class="welcome-msg"><?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getChildHtml('accountLinks') ?></p>` in [app/design/frontend/rwd/default/template/page/html/header.phtml](https://github.com/OpenMage/magento-mirror/blob/1.9.2.1/app/design/frontend/rwd/default/template/page/html/header.phtml#L39). Pretty often some theme developers just code some "Is user logged in then echo this, else echo that" hard into the templates.

**Comment by apantaleo** [comment]
<block type="page/html_header" name="header" as="header">
                <block type="page/template_links" name="top.links" as="topLinks"/>
                <block type="page/switch" name="store_language" as="store_language" template="page/switch/languages.phtml"/>
                <block type="directory/currency" name="currency_top" template="directory/currency.phtml"/>
                <block type="core/text_list" name="top.menu" as="topMenu" translate="label">
                    <label>Navigation Bar</label>
                    <block type="page/html_topmenu" name="catalog.topnav1" template="page/html/topmenu.phtml"/>
                </block>
				<block type="core/text_list" name="top.menu2" as="topMenu2" translate="label">
                    <label>Navigation Bar</label>
                    <block type="page/html_topmenu" name="catalog.topnav" template="page/html/topmenu.phtml"/>
                </block>
                <block type="page/html_wrapper" name="top.container" as="topContainer" translate="label">
                    <label>Page Header</label>
                    <action method="setElementClass"><value>top-container</value></action>
                </block>
                <block type="page/html_welcome" name="welcome" as="welcome"/>
            </block>


in header:
                        <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>

**Comment by Mic2005** [comment]
Do you use a special template or default Magento template?

**Comment by GordonLesti** [comment]
Better change `$this->getWelcome()` to `$this->getChildHtml('welcome')`. Welcome message has to be in it's own block to be dynamic or lazy.
