### ISSUE TITLE
customer session cahed 

### ISSUE THREAD

**Issue by sean1982** [GordonLesti/Lesti_Fpc#222]
when i log in as a customer and i then log out i go on a different page and it shows there still logged in and shows on all computers 
i also notice that when logged in some pages say that your not logged in 

has anyone any ideas what the issue is or can i disable module from caching these pages

**Comment by laxmishhstrapp** [comment]
After you log out, are you able to access the customer account? If not, it just means your top links block which shows Login information is not made dynamic. Identify this block and add in dynamic blocks.
