### ISSUE TITLE
how check if product have cache already by product id

### ISSUE THREAD

**Issue by OlgaBurtyka** [GordonLesti/Lesti_Fpc#224]
Hi! Thank you for your extension.
Can you, please, say me one thing. I used magento 1.4.
For clean cache by product  ID i used this code :

$fpcModel = Mage::getSingleton('fpc/fpc');
if (is_object($fpcModel)) {

    foreach ($arrayAllProductIds as $productIdForCleanCache) {
        $fpcModel->clean(sha1('product_' . $productIdForCleanCache));
    }
}
 How I can check if product have cache by product id already?
Thanks.

**Comment by GordonLesti** [comment]
Hello @OlgaBurtyka 
`Lesti_Fpc_Model_Fpc` is just extending from `Mage_Core_Model_Cache`, but this class has the function [getFrontend](https://github.com/OpenMage/magento-mirror/blob/magento-1.4/app/code/core/Mage/Core/Model/Cache.php#L316). This function will return an object of type `Zend_Cache_Core` and there exists the function [getIdsMatchingAnyTags](https://github.com/OpenMage/magento-mirror/blob/magento-1.4/lib/Zend/Cache/Core.php#L538) or maybe better [getTags](https://github.com/OpenMage/magento-mirror/blob/magento-1.4/lib/Zend/Cache/Core.php#L595). Maybe a possible solution for you can be
```php
$fpcModel = Mage::getSingleton('fpc/fpc');
$arrayAllProductIds = array_map(
        function($value) {
            return sha1('product_' . $value);
        },
        $arrayAllProductIds
    );
$arrayAllProductIds = array_intersect(
        $arrayAllProductIds,
        $fpcModel->getFrontend()->getTags()
    );
$fpcModel->clean($arrayAllProductIds);
```
I hope this will help you.

**Comment by OlgaBurtyka** [comment]
Thank you very much for your answer.
