### ISSUE TITLE
create FPC by product id  without visit product page

### ISSUE THREAD

**Issue by OlgaBurtyka** [GordonLesti/Lesti_Fpc#225]
Hi! Thank you for your answer on previous issue. I have last question.
How I can emulate visit product page and create fpc for product by product id. For example i have array with product id, and for this id need create fpc without visiting product page. Thank you.

**Comment by GordonLesti** [comment]
Hello @OlgaBurtyka 
creating cache without visiting the page isn't that easy or maybe impossible. FPC is caching by the event `http_response_send_before`.
