### ISSUE TITLE
cart add/apply coupon/update

### ISSUE THREAD

**Issue by jroca22** [GordonLesti/Lesti_Fpc#227]
Hi,
I'm having problems with the module when adding an item to the cart from product listing page. From product page the module adds with no problem.
product listing: http://retrosuperfuture.com/default/shapes/flat-top.html
product page: http://retrosuperfuture.com/default/shapes/flat-top/t4d-afj
now the module is disabled.
Can you please help me? Magento goes pretty fast with this Fpc module.
Thanks,
Juan

**Comment by GordonLesti** [comment]
Hello @jroca22 
it's difficult to find a bug with disabled Fpc. I'm not sure if that can be the reason, but I have noticed that the request from product list is missing the `form_key`. Maybe it is better to contact me via email.

**Comment by jroca22** [comment]
Hi GordonLesti,
I sent you an e-mail at info@gordonlesti.com.
Thanks
