### ISSUE TITLE
Cart Speed

### ISSUE THREAD

**Issue by Webmasterei** [GordonLesti/Lesti_Fpc#229]
Hi, 
we're running a large magento store and have lesti FPC in use. Everything runs well but the cart. 

The cart is exluded of the caching process. I wonder if there is a senseful way to session-cache the cart with the outlined update handels or if this is not a good idea. 

Yet we could not find the reason the cart using so much mysql requests....

Thanks for your aprreciated advise.

Bernhard

**Comment by GordonLesti** [comment]
Hello @Webmasterei 
is your cart a dynamic or a lazy block at the moment? Were did you store your session, database or redis, or ...?

**Comment by Webmasterei** [comment]
Hi Gordon,
I added checkout_cart_index in the cachable actions and put 
checkout.cart as a lazy block.
This way, a session has it's own cart. If I canche things in the cart. 
Everything is ok.
If I add an item from product detail into the cart the cart doesn't get 
refresehd.

My refresh actions are:
checkout_cart_add,
checkout_cart_delete,
checkout_cart_updatePost,
catalog_product_compare_add,
catalog_product_compare_clear,
catalog_product_compare_remove,
wishlist_index_add,
wishlist_index_remove,
wishlist_index_update,
wishlist_index_allcart,
wishlist_index_configure,
checkout_onepage_success,
poll_vote_add,
checkout_cart_product_add_after

Thanks for helping.

**Comment by Webmasterei** [comment]
....that's just the problems I was running into yesterday.... maybe you can help with that. 

To answer your previous questions:
Dynamic Block works well (but I'd like to have it lazy).
Session is Redis cached.

**Comment by GordonLesti** [comment]
Can it be that you have a ajax based add to cart button?

**Comment by Webmasterei** [comment]
jip.

**Comment by Webmasterei** [comment]
I'm using https://github.com/webcomm/magento-boilerplate

**Comment by GordonLesti** [comment]
[webcomm/magento-boilerplate](https://github.com/webcomm/magento-boilerplate) doesn't seem to have a ajax based add to cart button. Are you sure that your add to cart button is from this template?

**Comment by Webmasterei** [comment]
Hi Gordon, good hint! It's I took antother button.

This is what the button looks like:

<div class="add-to-box">
<div class="add-to-cart">
<div class="input-group">
<span class="input-group-btn">
<button type="button" class="btn btn-default btn-number" 
disabled="disabled" data-type="minus" data-field="qty">
<i class="fa fa-minus"></i>
</button>
</span>
<input type="text" name="qty" id="qty" maxlength="12" max="999999999" 
min="1" value="1" title="Menge" class="input-number form-control qty">
<span class="input-group-btn">
<button type="button" class="btn btn-default btn-number" 
data-type="plus" data-field="qty">
<i class="fa fa-plus "></i>
</button>
<button type="button" title="Warenkorb" class="button btn btn-cart" 
onclick="productAddToCartForm.submit(this)">
<i class="fa fa-cart-plus"></i>&nbsp;Warenkorb</button>
</span></div>
</div>
</div>


How to find the right action?

**Comment by GordonLesti** [comment]
A pretty easy solution to detect the action is logging in [Lesti_Fpc_Model_Observer::controllerActionPostdispatch](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Model/Observer.php#L179) after line 179:
```
Mage::log($fullActionName, null, 'action.log', true);
```
After adding a product to the cart, you should see a entry in the log file `var/log/action.log` with the right action.

**Comment by Webmasterei** [comment]
The Action Log says it is "checkout_cart_add", which is in the Refresh 
Actions...

**Comment by GordonLesti** [comment]
Spooky, can you start logging/debugging if the application crosses this line https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Model/Observer.php#L184 ?

**Comment by GordonLesti** [comment]
@Webmasterei can I close this issue?

**Comment by Webmasterei** [comment]
Hi Gordon, 
I could not resolve this yet but yeah - close it. 

Thanks for your help.

**Comment by Webmasterei** [comment]
What do you mean by "crosses line?"

**Comment by GordonLesti** [comment]
The lazy blocks will be invalidate, if the application passes the line 184 of [Lesti_Fpc_Model_Observer::controllerActionPostdispatch](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Model/Observer.php#L184). It's a mystery to me why your cart isn't working as lazy block if the action is `checkout_cart_add` and `checkout_cart_add` is contained in the config as `Refresh Actions`.
