### ISSUE TITLE
Filters get pre-applied on category page

### ISSUE THREAD

**Issue by laxmishhstrapp** [GordonLesti/Lesti_Fpc#230]
Hi Gordon,

We have been using Lesti FPC on most our clients' websites. It has been working wonders. However, we have an issue on our latest project. The problem is, layered navigation filters get pre-applied on some category pages. I do not know why this is happening.

We are using manadev layered navigation. **Add layered nav atttributes to URL params** is set to Yes. I have manually added all the attributes as well.

I don't know how to re-produce the bug. But this is what is happening:

1. Flush all cache
2. Go to http://www.amarchitrakatha.com/us/tinkle
3. Filters are not pre-applied. Everything is normal.
4. Try applying filters. Filters get applied properly.
5. Refresh page, filters persist. EVERYTHING NORMAL.
6. **Wait for a day.**
7. Open the same page
8. You can see pre-applied filters. NOT NORMAL, Why?

To see the bug in action, **you can visit the above page now**. Will appreciate any help :-)

Our application info:
Magento Community 1.9.0.1
Cache and session stored in Redis
Manadev Layered Navigation
**No varnish** or other kind of cache

**Comment by GordonLesti** [comment]
Hello @laxmishhstrapp 
I can't see pre-applied filters at the moment.

**Comment by laxmishhstrapp** [comment]
I made this fix:
http://magehero.com/posts/738/fix-for-lesti-fpc-manadev-seo-layered-navigation
Looks like its working now. I will wait or a day and report here.

**Comment by laxmishhstrapp** [comment]
Its working after magehero fix :-)

**Comment by GordonLesti** [comment]
Good to know that it works. You can also use the event [fpc_helper_collect_params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.5/app/code/community/Lesti/Fpc/Helper/Data.php#L107) to add `Mage::registry('m_parsed_url')` as param.
