### ISSUE TITLE
Category filtering does not work

### ISSUE THREAD

**Issue by Insect2015** [GordonLesti/Lesti_Fpc#231]
hello Support,

When I go to the category page I cannot filtering on a sub-category.

See url: https://www.ksb-denbosch.nl/gebruikt-inrichten/gebruikte-kasten
When you click on "Lockerkast (3)" it's not filter the items.

**Comment by GordonLesti** [comment]
Hello @Insect2015 
* `cat` is part of your Uri Params?
* Magento version?
* Fpc version?

**Comment by Insect2015** [comment]
Hello @GordonLesti 

`cat` was not part of my Uri Params I have add it to the Uri params!

Thanks!
