### ISSUE TITLE
Incorrect module version

### ISSUE THREAD

**Issue by p-makowski** [GordonLesti/Lesti_Fpc#232]
Please increase module version accordingly to Semantic Versioning (http://semver.org/).
Otherwise composer projects defining dependency on "lesti/fpc" and using only "stable" tagged modules are not aware of all good changes done since 1.4.5 in master.

**Comment by siment** [comment]
This is a great suggestion

**Comment by GordonLesti** [comment]
Thanks for the hint, [1.4.6](https://github.com/GordonLesti/Lesti_Fpc/releases/tag/1.4.6) is released.

**Comment by p-makowski** [comment]
@GordonLesti 
Thanks for instant action. 
As I see there is still 1.4.5 in Lesti_Fpc/app/code/community/Lesti/Fpc/etc/config.xml
I didn't check how you did it previously, but probably you followed a great rule of having repository version and Magento version equal. Is that something you accidently missed out?

**Comment by GordonLesti** [comment]
@p-makowski yes, you are right.

**Comment by GordonLesti** [comment]
maybe I will close this issue again. I hope this is no issue for anybody. I will synchronize Magento version with the Github release again in the next version.
