### ISSUE TITLE
Store switcher based on GeoIP not working

### ISSUE THREAD

**Issue by hashid** [GordonLesti/Lesti_Fpc#234]
Hi Gordon,

Thanks for this amazing extension and the support you have been providing. We have found an issue with our international Magento store. This is the scenario:

1. We have 3 websites India, US, and International on a **single Magento instance**.
2. We have 3 website urls like:
www.store.com/in
www.store.com/int
www.store.com/us
When visitors go to www.store.com, they are redirected to one of the above url **based on their IP.**
We are using Ipstoreswitcher module from **Atwix** for this purpose.
3. The problem is, when FPC is turned on all users are redirected to the default website (/in) independent of their IP. I think the observer which handles the logic for redirection is not getting fired since this request might be cached.
4. However, everything works fine if FPC is disabled.
5. How do I solve this?

You can see the Ipstoreswitcher code here:
https://www.atwix.com/magento/geoip-magento-store-switcher/

Will appreciate any help.

**Comment by GordonLesti** [comment]
Hello @hashid 
you can use the event [fpc_helper_collect_params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/Helper/Data.php#L107) to add the resolved storeId of your module to `$parameters` array. I hope this will help you.
