### ISSUE TITLE
cms can't be cleaned

### ISSUE THREAD

**Issue by breakerh** [GordonLesti/Lesti_Fpc#236]
I'm trying to clean the cms page (or actually only the homepage). But for some reason it doesn't want to clean it.

I tried the following code inside a IndexController:
```
    $fpc = Mage::getSingleton('fpc/fpc');
    $fpc->clean(array(sha1('cms')));
    $fpc->clean(array(sha1('cms_index_index')));
    $fpc->clean(array(sha1('cms_page_view')));`
```

But nothing works. I hope i'm just doing something wrong but i guess it's a bug?
Flushing the cache in the backend does work btw.

Thanks in advance!

**Comment by GordonLesti** [comment]
```
 $fpc->clean(array(sha1('cms')));
```
will clean all CMS pages
```
 $fpc->clean(array(sha1('cms' . $pageId)));
```
will clean a specific CMS page. Please note that Magento is maybe also caching stuff on the page, for example the block cache.

**Comment by breakerh** [comment]
Thank you, will try again :)
