### ISSUE TITLE
FPC slows down backoffice

### ISSUE THREAD

**Issue by wdttilburg** [GordonLesti/Lesti_Fpc#237]
At the moment we've installed FPC but when we save a product in de backoffice it takes a lot off time to reload. When we disable FPC is much faster.

**Comment by GordonLesti** [comment]
Hello @wdttilburg 
I'm sorry, but that FPC uses the event `catalog_product_save_after` to clean the cache from the saved product.There is no workaround for your problem.

**Comment by barryvdh** [comment]
Is it possible to create an option to disable the automatic flushing of the cache?
We are importing with the API, and FPC is slows down massively (eg. 15+ seconds on a save per call). 

I can disable the events manually now, by removing them from config.xml, but an option would be nice.

And ideally an option to flush the cron nightly, or with an API call. Is that possible to implement?

**Comment by GordonLesti** [comment]
Hello @barryvdh 
it is possible, but for me personally the options and settings of FPC are too much at the moment. I would recommend to disable a observer with something like that for example
```
<?xml version="1.0"?>
<config>
    <modules>
        <MyNamespace_MyModule>
            <version>0.1.0</version>
        </MyNamespace_MyModule>
    </modules>
    <global> <!-- Be careful to use <frontend> like above, <global> would not work -->
        <events>
            <catalog_product_save_after>
                <observers>
                    <fpc_catalog_product_save_after>
                        <type>disabled</type>
                    </fpc_catalog_product_save_after>
                </observers>
            </catalog_product_save_after>
        </events>
    </global>
</config>
```
This example is taken from [Disable an event observer defined by default in Magento](http://www.bubblecode.net/en/2012/01/21/disable-an-event-observer-defined-by-default-in-magento/) by @jreinke
