### ISSUE TITLE
Bypass Handles - CMS Page

### ISSUE THREAD

**Issue by JamesSimpson** [GordonLesti/Lesti_Fpc#238]
I've been digging through the code, but thus far have been unable to find this part...

Is it possible to add a CMS page to the bypass handles, like you do with a category (CATEGORY_#ID#)?

Thanks

James

**Comment by GordonLesti** [comment]
Hello @JamesSimpson 
unfortunately that is not possible, Magento isn't adding a handle like `CMS_PAGE_#ID#`. An other possible ways would be to use the `Miss Uri Params`, for example `id=/^6$/` for the CMS page with id `6`. But unfortunately this would also ignore products with id `6`. I'm very sorry that there is no other way that I can think of at the moment.

**Comment by JamesSimpson** [comment]
Hi @GordonLesti - Thanks for getting back to me, and a great plugin :)
That would be ok, but in my case, it doest seem to work for the home page (as there is a block on there i cannot get to hole punch at all when the reset button is pressed).

**Comment by GordonLesti** [comment]
What a reset button? Whit homepage did you mean `cms_index_index`?

**Comment by Mic2005** [comment]
I think clear Magento Cache ;)

**Comment by JamesSimpson** [comment]
Hi Gordon,

Basically there is a html form on the home page to fill in, to find parts. Once the parts are found, the user can go back to the home page and the form is still filled in, but has a reset button to clear the contents of the form. Clicking the reset button with the FPC enabled does not clear the form, but with FPC disabled, it works fine.

The form is on the home landing page cms_index_index.

The plugin i am talking about is this: https://amasty.com/product-parts-finder.html

**Comment by JamesSimpson** [comment]
I have also tried inserting the "block name" into the back end configuration of FPC, but that does not work either, so my only solution I can see is to make the home page not cached, but the id=/^3$/ does not work, where 3 is the home page CMS id

**Comment by GordonLesti** [comment]
Hello @JamesSimpson 
ignoring the handle `cms_index_index` is pretty easy by removing this handle from the cacheable actions in the config of FPC.
