### ISSUE TITLE
custom login block throwing error with lesti activated

### ISSUE THREAD

**Issue by Webmasterei** [GordonLesti/Lesti_Fpc#239]
Hi Gordon, 
I added lestifpc to a new site. It had in header.phtml the code
`<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customer_form_mini_login')->toHtml(); ?>`
Which I know it wouldn't work so I swapped to:
`<?php echo $this->getChildHtml('customer_form_mini_login'); ?>`
With this layout block setup:
`<block type="customer/form_login" name="customer_form_mini_login" as="customer_form_mini_login" template="customer/form/mini.login.phtml">
                    <block type="cms/block" name="callout">
                        <action method="setBlockId"><block_id>callout</block_id></action>
                    </block>
                </block>`

Last I tried adding it to dynamic block or to lazy block but both does not work. The first load is ok, but then I get a fatal error on login.php
`Fatal error: Call to a member function setTitle() on a non-object in .../app/code/core/Mage/Customer/Block/Form/Login.php on line 40`

which contains:
`        $this->getLayout()->getBlock('head')->setTitle(Mage::helper('customer')->__('Customer Login'));
`

Any Idea what could cause this?
Thanks for your help!

**Comment by GordonLesti** [comment]
Hello @Webmasterei 
yes, FPC is creating something like a light-layout, which only contains dynamic & lazy blocks. So `$this->getLayout()->getBlock('head')` will return `null`. Did that explanation help you?

**Comment by Webmasterei** [comment]
Yes & No.... I'm not seeing the consequences yet. How to work around? 
Not cache a login box?

**Comment by GordonLesti** [comment]
Not easy to answer without a deeper look. Better don't use a child block of the header to change the title of the header block. Can you describe the task of this block a little bit more detailed?

**Comment by Webmasterei** [comment]
It is a sitewide login/logout box. It propably tries to write title 
beause it's the login process attached.

**Comment by Webmasterei** [comment]
This is, what it does.....

<?php /** * Magento * * NOTICE OF LICENSE * * This source file is 
subject to the Academic Free License (AFL 3.0) * that is bundled with 
this package in the file LICENSE_AFL.txt. * It is also available through 
the world-wide-web at this URL: * 
http://opensource.org/licenses/afl-3.0.php * If you did not receive a 
copy of the license and are unable to * obtain it through the 
world-wide-web, please send an email * to license@magentocommerce.com so 
we can send you a copy immediately. * * DISCLAIMER * * Do not edit or 
add to this file if you wish to upgrade Magento to newer * versions in 
the future. If you wish to customize Magento for your * needs please 
refer to http://www.magentocommerce.com for more information. * * 
@category design * @package rwd_default * @copyright Copyright (c) 2014 
Magento Inc. (http://www.magentocommerce.com) * @license 
http://opensource.org/licenses/afl-3.0.php Academic Free License (AFL 
3.0) */ ?><div class="block block-login block-login-<?php echo 
Mage::app()->getStore()->getLocaleCode(); ?>"> <?php echo 
$this->getLayout()->createBlock('cms/block')->setBlockId('callout')->toHtml(); 
?><form class="mini-login" action="<?php echo $this->getPostActionUrl() 
?>" method="post"> <div class="block-content"> <?php if 
((Mage::getSingleton('customer/session')->isLoggedIn())): ?><div 
class="block-title" style="float:right;"> <strong><span><a href="<?php echo 
Mage::getBaseUrl().'customer/account/logout'?>" style="color:white;"><?php echo $this->__('Abmelden') ?></a></span></strong> </div> 
<?php else: ?><div class="block-title"> <strong><span><?php echo 
$this->__('Anmelden:') ?></span></strong> </div> <input type="email" 
autocapitalize="off" autocorrect="off" spellcheck="false" 
name="login[username]" id="mini-login" class="input-text" 
placeholder="<?php echo $this->__("Email Address"); ?>" /> <input 
type="password" name="login[password]" id="mini-password" 
class="input-text" placeholder="<?php echo $this->__("Password"); ?>" /> 
<?php echo $this->getBlockHtml('formkey'); ?><div 
class="forgot-password"> <span> <a href="<?php echo 
Mage::helper('customer')->getForgotPasswordUrl(); ?>">[<?php echo $this->__("Forgot Your Password?"); ?>]</a>&nbsp; <a href="<?php echo 
Mage::helper('customer')->getRegisterUrl(); ?>">[<?php echo $this->__("Register now"); ?>]</a> </span> </div> <div class="actions"> <button type="submit" 
class="button login"><span><span><?php echo $this->__('Login') 
?></span></span></button> </div> <?php endif; ?><?php if 
((Mage::getSingleton('customer/session')->isLoggedIn())): ?><div 
class="account"> <div class="image"> <a href="<?php echo 
Mage::getUrl("customer/account"); ?>"> <img src=<?php echo 
$this->getSkinUrl("images/../account.png") ?>alt="<?php echo 
$this->__("My Account") ?>" title="<?php echo $this->__("My Account") 
?>"/> </a> </div> <div class="text"> <strong> <span><a href="<?php echo 
Mage::getBaseUrl().'customer/account'?>" style="color:white;"><?php echo $this->__('Customer Account') ?></a></span> </strong> 
</div> </div> <?php endif; ?><div class="clearfix"></div> </div> </form> 
<div class="clearfix"></div> </div>

Not my code....

**Comment by GordonLesti** [comment]
> Not my code....
:)
This is confusing to me. Is this block just editing the title of the header? Why should it be dynamic or lazy?

**Comment by Webmasterei** [comment]
so true... It turned out the bent the login form into the header, while login.php is called and so -BÄÄM! It's been ignored without your FPC, anyway I commented the line in questions and now it's ok.

**Comment by subodhkalika** [comment]
@GordonLesti @Webmasterei Hi, I am facing the same issue. You commented the line and the problem gets solved but i cant comment it cause i cant modify the core magento code. Kindly provide a workaround or better solution if you have come accross any .

**Comment by wmsanjaya** [comment]
Hi I faced the same issue and managed to fix it by creating a custom mini login form. In this way didnt have to hack the core code.

`<reference name="customer_dynamic_block">
	<block type="page/html" name="custom_form_mini_login" as="home_customer_mini_form" template="customer/form/custom.login.phtml"></block>
	<reference name="custom_form_mini_login">
		<action method="setTemplate"><template>rememberme/form/mini.login.phtml</template></action>
	</reference>
</reference>`
