### ISSUE TITLE
Error 500 after installing extension

### ISSUE THREAD

**Issue by Charlie721** [GordonLesti/Lesti_Fpc#240]
Hello,
previously I had mirasvit ful page cache which I disabled and I installed yours ful page cache extension manually by copying app folder to my magento app folder. After that my site and site admin are broken and I can not access them anymore. When I try to acces web page or admin I get error 500. I also tried to remove all files that were copied from your extension but I get the same error 500.

Any suggestions?
Thanks

**Comment by GordonLesti** [comment]
Hello,
please check the webserver error log. What is the message of the 500 error?

**Comment by Charlie721** [comment]
In error_log I only see this message [18-Jun-2016 07:27:50 UTC] PHP Fatal error:  Call to a member function addMessages() on a non-object in /home/mydomain/public_html/includes/src/__default.php on line 14498

**Comment by GordonLesti** [comment]
Please disable/refresh Magento compiler. And clear Magento cache.

**Comment by Charlie721** [comment]
Hi, when I cleared cache manually everything works fine, thanks. But now I'm back without your extension because I removed it manually. I'm affraid but what do you mean. Should I try to install it again and how to avoid the same problem happening? Maybe just to try clear the cache manually after installing your extension? Would it be better to remove mirasvit extension or is it ok to just leave it disabled?
Thanks

**Comment by GordonLesti** [comment]
Hello,
in general I would recommend testing extensions on a staging/test or local system. If installing again, please disable Magento compiler before. In general I would always recommend removing unused code or extensions.

**Comment by Charlie721** [comment]
OK, thank you.
