### ISSUE TITLE
Product not in category

### ISSUE THREAD

**Issue by Mic2005** [GordonLesti/Lesti_Fpc#242]
Hi Gordon, I try to activate a product on frontend but it's not vissible in the categorie? When i look to the category response headers the age is 5946. I flushed the cache before but age still 5946. Strange because other categories have Age 0. I deactivated some categories in the product config and activated them, safe product. Also reindex Indexed category/products association did not solve the fault. Any idea? 
Magento 1.9.2.4, Redis cache, FPC and PHP7

Regards, Micha

**Comment by GordonLesti** [comment]
Hello @Mic2005 
did you have something like a proxy in front of the webserver or http cache of category pages for browsers enabled?

**Comment by Mic2005** [comment]
Close down this issue.  Next day it was working.  No proxy here.

**Comment by GordonLesti** [comment]
happens :smile:
