### ISSUE TITLE
Cache gets clear after nativation

### ISSUE THREAD

**Issue by petnutz** [GordonLesti/Lesti_Fpc#243]
Ok so my problem is like that, when i go to a page and load it , it takes like 9seconds to load, after refresh again its arround 1.5seconds which is amazing, but if i navigate to another page and then back to the "cached" page it again 9seconds and second refresh fix it again. So it seems the cache its not saved or not used which makes it uneffective.
i wonder if i do something wrong or anyone encounter that kind of problem in the past and knows how to fix it.
bests

**Comment by GordonLesti** [comment]
Hello @petnutz 
this can happen when the generated key for the page is different, you can debug at that in [Lesti_Fpc_Helper_Data::_getParams](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/Helper/Data.php#L110).
