### ISSUE TITLE
How to enable TB Developer Toolbar

### ISSUE THREAD

**Issue by icbrg** [GordonLesti/Lesti_Fpc#244]
How is the best way to deal with TB Developer toolbar with Lesti FPC? I tried to put:
TB_Develop_Block_Toolbar,
TB_Develop_Block_Dashboard,
TB_Develop_Block_Layouts,
TB_Develop_Block_Blocks

in dynamic blocks but nothing, I must do something more?

**Comment by GordonLesti** [comment]
Hello,
please make sure to use the name in layout of a block, not the class name.
