### ISSUE TITLE
Add custom block from startpage to lazy blocks

### ISSUE THREAD

**Issue by kledy** [GordonLesti/Lesti_Fpc#245]
On homepage I use customs blocks with products from varies categories:
{{block type="catalog/product_list" category_id="1111" template="catalog/product/list_home.phtml"}}

When changing the sort order or other things in this category, the changes are not visible in this block. How can I add this blocks to lazy blocks? Or is it possible to renew automaticaly the output from this block, when change and save the category?

Thanks for your help!

**Comment by GordonLesti** [comment]
Hello @kledy 
I'm not completely sure, but maybe a possible solution can be to add the category id tag if present at  [Lesti_Fpc_Helper_Block::getCacheTags](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/Helper/Block.php#L123). Are you interested to test that and maybe create a PR?
