### ISSUE TITLE
$cacheTags: which functions need to be adjusted for additional cache tag product price?

### ISSUE THREAD

**Issue by marcopolo88** [GordonLesti/Lesti_Fpc#246]
if I wanted to add the current product price as an additional cache tag to the function
getCatalogProductViewCacheTags.
$_product = Mage::getModel('catalog/product')->load($productId)); 
$cacheTags[] = sha1($_product->getFinalPrice());

Would that be enough to have a new product price automatically a new key and cache-item triggered or is there another spot in the code that would need adjustment? 

(the price change is not necessarily due to an magento action which can be observed)
I dont mind having to use more keys used and larger cache on disk stored

**Comment by GordonLesti** [comment]
Hello @marcopolo88 
I'm sorry, but I didn't understand what you mean. Why did you want to add the product price as cache tag?

**Comment by marcopolo88** [comment]
pretty sure i had a wrong understanding
