### ISSUE TITLE
Megamenus disappears

### ISSUE THREAD

**Issue by informundo** [GordonLesti/Lesti_Fpc#249]
With Lesti fpc cache 1.4.5 enabled, every 2 days or so, does not show the megamenupro of emthemes. After refresh manually Lesti fpc and show it again. I have tried every configuracions, but currently do not have the block where will the MegaMenu in any configuration, neither lazy nor dynamic. I have a php file to refresch cache every days via cron, but  lesti fpc don´t refresh. I use this to refresh cache:
```
// 2 CLEAN CACHE
Mage::app()->cleanCache();
try {
    $allTypes = Mage::app()->useCache();
    foreach($allTypes as $type => $blah) {
      Mage::app()->getCacheInstance()->cleanType($type);
    }
} catch (Exception $e) {
    echo $e->getMessage();
}
```
Thanks.
Marcos
https://www.navatiendas.es

**Comment by GordonLesti** [comment]
Hello @informundo 
I'm sorry, but your menu is a paid extension with closed source code. In general I would not recommend to make menu dynamic or lazy. The lazy and dynamic blocks are mostly just for customer specifically content.
Your examples from above aren't working, cause FPC is separated cache instance. That makes it possible to have different cache backends with different configs. Redis for FPC, memcached for Magento for example. You can clean FPC with:
```
Mage::getSingleton('fpc/fpc')->clean();
```
I hope this will help you.
