### ISSUE TITLE
n98-magerun Does Not Flush Cache (Redis)

### ISSUE THREAD

**Issue by sprankhub** [GordonLesti/Lesti_Fpc#250]
Thanks for your awesome extension!

I have an issue which may be related to Lesti_Fpc. It is basically described in a [n98-magerun issue](https://github.com/netz98/n98-magerun/issues/775) (and a [related issue](https://github.com/netz98/n98-magerun/issues/613)). When using Redis, a `n98-magerun.phar cache:flush` does not fully clear the cache. In the linked issue, specifically [here](https://github.com/netz98/n98-magerun/issues/775#issuecomment-188440724) Tom says that this seems to be related to your extension. Could you please have a look and check?

Thanks again!

**Comment by emateu** [comment]
I have the same problem, not sure why.

A quick solution for me was manually adding `\Mage::getSingleton('fpc/fpc')->getFrontend()->clean('all')` to my own script.

Seems that n98-magerun is not triggering (not sure if should)
`Lesti_Fpc_Model_Observer_Clean::controllerActionPredispatchAdminhtmlCacheMassRefresh`

Also when I clean programmatically caches (code below), Lesti_Fpc is not cleaned too:
````
$allTypes = \Mage::app()->useCache();
foreach($allTypes as $type => $blah) {
    \Mage::app()->getCacheInstance()->cleanType($type);
    \Mage::dispatchEvent('adminhtml_cache_refresh_type', array('type' => $type));
}
````

Hope this information helps. I'm using Redis.

**Comment by GordonLesti** [comment]
Hello @sprankhub 
yes, I guess FPC should maybe use event [application_clean_cache](https://github.com/OpenMage/magento-mirror/blob/1.9.2.4/app/code/core/Mage/Core/Model/App.php#L1191).

**Comment by sprankhub** [comment]
@GordonLesti could you already have a deeper look at this issue?

**Comment by GordonLesti** [comment]
Hello @sprankhub 
as mentioned above I guess FPC listening to the event [application_clean_cache](https://github.com/OpenMage/magento-mirror/blob/1.9.2.4/app/code/core/Mage/Core/Model/App.php#L1191) should fix this BUG. But unfortunately I have just limited time at the moment to fix this (Cruciate ligament). What about, I try to fix this in a extra branch and you may test it?

**Comment by sprankhub** [comment]
Sure. If you implement it, I am happy to test and to give you feedback.

**Comment by ktomk** [comment]
In case Magerun misses to call/trigger the "`application_clean_cache`" event, and you need this for testing the fix (e.g. from CLI as well next to Mageto Adminhtml) you can ping me anytime and I can put it into the development (unstable) version for an easy test.

**Comment by GordonLesti** [comment]
I made a small research. Here a list of all events that are dispatched when running the command `n98-magerun.phar cache:flush`:
* `resource_get_tablename`
* `core_collection_abstract_load_before`
* `core_collection_abstract_load_after`
* `adminhtml_cache_flush_all`
* `application_clean_cache`

I guess the best candidate is `adminhtml_cache_flush_all`. It is also dispatched in [Mage_Adminhtml_CacheController::flushAllAction](https://github.com/OpenMage/magento-mirror/blob/1.9.2.4/app/code/core/Mage/Adminhtml/controllers/CacheController.php#L56).

**Comment by sprankhub** [comment]
Thanks! Sounds reasonable :+1:

**Comment by ktomk** [comment]
Great news!
