### ISSUE TITLE
Lesti FPC not showing up in backoffice configuration

### ISSUE THREAD

**Issue by JensBourgeois** [GordonLesti/Lesti_Fpc#254]
After installing the module using modman, clearing my caches and logging out and logging back in again, the module does not show up in the backoffice.

Any idea what's wrong?

We are using Magento v1.9.2.2

**Comment by GordonLesti** [comment]
Hello @JensBourgeois 
are the symlinks of modman present? What does Magento say? Is the module listed in Configurations => System => Advanced?

**Comment by JensBourgeois** [comment]
Yeah, we've got alot of modules deployed using modman, the symlinks are present and the module is listed and seems to be working as well. (site is going much faster)

I've managed to get it working by editing the system.xml myself (and adding the <acl> sections in the config.xml)

![screen shot 2016-09-02 at 08 37 10](https://cloud.githubusercontent.com/assets/12065231/18194784/78920b1c-70e8-11e6-945f-08401de05d32.png)

**Comment by GordonLesti** [comment]
The configs should be part of the section `system`. I guess your modified system.xml will not work, cause you have changed the path for the configs.
