### ISSUE TITLE
No Admin Configuration Section

### ISSUE THREAD

**Issue by JonnaIsaac01** [GordonLesti/Lesti_Fpc#256]
Hi,

I've installed the extension, and I see the enabled module (Lesti_Fpc) in System > Config > Advanced > Advanced. I also see the Fpc cache enabled in Cache Management, however, I don't see the configuration panel in Admin panel - Config - System - Lesti FPC section.

I'm running Magento 1.9.2.4 and PHP 5.6.10. I've installed the extension manually, and have tried installing in app/design/frontend/base, as well as app/design/frontend/rico ('rico' is the theme), and have been sure to clear the cache and log in and out after modifying, and loading app/etc files last. 

Any ideas why this panel would be missing?

Thanks,
Jonna

**Comment by JonnaIsaac01** [comment]
Hi,

Just discovered this existing issue: https://github.com/GordonLesti/Lesti_Fpc/issues/233

So there is no config panel (Admin panel - Config - System - Lesti FPC section), just the Fpc cache in Admin panel - Config - Cache Management?

Thanks!

**Comment by GordonLesti** [comment]
Hello @JonnaIsaac01 
thank you. I have changed the path to the configs.
