### ISSUE TITLE
Question header.welcome

### ISSUE THREAD

**Issue by Mic2005** [GordonLesti/Lesti_Fpc#260]
Hi @GordonLesti you wrote in #214 
.... NEVER put a block into dynamic and lazy, only one.

We updated to the last version today because every customer see my testaccount name at the frontend :(
I see in my config that there are 5 (!) actions standing into Lazy and Dynamic Blocks. Is this wrong?
What to put where?

![image](https://cloud.githubusercontent.com/assets/11639487/19317552/adf8059a-90a5-11e6-8529-fc479f9bed6a.png)

![image](https://cloud.githubusercontent.com/assets/11639487/19317651/ff9ee99a-90a5-11e6-8031-30ea1b4178b4.png)

Hope you can advice me.

Thanks

**Comment by GordonLesti** [comment]
Hello @Mic2005 
yes. A block should be only in Lazy XOR Dynamic blocks, but never in both. Maybe this [post](http://gordonlesti.com/what-are-lazy-and-dynamic-blocks-in-lesti-fpc/) can help you to understand the main difference between those types. If you aren't sure what to choose, dynamic blocks works in the most cases, lazy depends much on the actions that refreshes the blocks.

**Comment by Mic2005** [comment]
Thanks for your quick response Gordon.
I have read the post and removed some actions in Dynamic Blocks because in your example I saw those actions set in Lazy Blocks. I think my previous hoster did some tuning in fpc :(

**Comment by GordonLesti** [comment]
I hope your problem is solved now. You are welcome.

**Comment by Mic2005** [comment]
No it's not, please look at https://www.babyandmore.eu it's back again.

**Comment by GordonLesti** [comment]
The basket seems to work for me. What does not work?

**Comment by Mic2005** [comment]
Go to the homepage. Strange that it's only on the homepage and not in the categories.

**Comment by GordonLesti** [comment]
What Magento version did you run?

**Comment by Mic2005** [comment]
1.9.2.4 and your last FPC version

**Comment by Mic2005** [comment]
If i switch the fpc off in magento cache this issue is gone.

**Comment by GordonLesti** [comment]
Please contact me via email or everybody will unwatch the issues in future :)

**Comment by Mic2005** [comment]
ok

**Comment by Mic2005** [comment]
Added "welcome" to Dynamic Blocks. Looked at xml for blockname: app/design/frontend/(template)/(template)/layout/local.xml
``<block type="page/html_welcome" name="welcome" as="welcome"/>``
