### ISSUE TITLE
Cache The Cart Page

### ISSUE THREAD

**Issue by JamesSimpson** [GordonLesti/Lesti_Fpc#261]
Is there a way we can cache the cart page, but hole punch the actual products and prices parts as I'm trying to improve the speed of this page, but at the moment its not cached at all (for obvious reasons)

**Comment by GordonLesti** [comment]
I guess that is maybe possible, but I wouldn't recommend it. You can try it by adding `checkout_cart_index` to the `Cachable actions` and by adding `checkout.cart` and `additional.product.info` to the `Dynamic Blocks`, but I'm sure if the result works.
