### ISSUE TITLE
Clear cache on homepage

### ISSUE THREAD

**Issue by r14smit** [GordonLesti/Lesti_Fpc#263]
We are running a daily deal on our homepage, unfortunately it is cached, so it is not really refreshed after finishing. Is there a way to clear the cache on the homepage.

I tried to use the Lazy and Dynamic blocks, but that didn't work.

**Comment by GordonLesti** [comment]
Did you mean manuell or via code?

**Comment by r14smit** [comment]
Via code, or even parameter in url

**Comment by r14smit** [comment]
Maybe there is even some kind of cron to run which can be set on a set time

**Comment by GordonLesti** [comment]
I guess that should clean the homepage CMS page
```
$pageId = Mage::getStoreConfig( Mage_Cms_Helper_Page::XML_PATH_HOME_PAGE );
Mage::getSingleton('fpc/fpc')->clean(sha1('cms_' . $pageId));
```
