### ISSUE TITLE
Consistent blank popup

### ISSUE THREAD

**Issue by philb1977** [GordonLesti/Lesti_Fpc#264]
Hi,

I have googled this until I'm blue in the face without any joy so I'm hoping someone here may be able to help as I'm eager to get the FPC up and running.

When we turn on the Lesti FPC cache every page loads with a blank popup. Once you click off that the page is fine but then it appears again when you go to another page.

Is this something anyone has come up against before? Any clues.

The cache is currently turned off due to the problem but the website is https://painandpleasure.co.uk

Any suggestions would be greatly appreciated as my technical knowledge is rather limited.

Thanks in advance

**Comment by GordonLesti** [comment]
Hello @philb1977 
I'm sorry, but that are way too less information to help you. I need a little bit more technical and detailed information.
But my first guess is, that your `Youama Ajax Login and Register` module is maybe _out of the box_ not compatible with FPC.

**Comment by GordonLesti** [comment]
You can try to add `youamaajaxlogin` as dynamic block.

**Comment by philb1977** [comment]
Hi there,

Wow well that did the trick instantly.... Thank you so much, you have no idea how much hair you've saved me!!
Kudos on such a great piece of software too :)

Forever greatfull
Phil
