### ISSUE TITLE
menu with variations in a configurable product disappear after the first visit to page

### ISSUE THREAD

**Issue by triplexita** [GordonLesti/Lesti_Fpc#265]
HI, with lesti fpc enabled i have this problem.
when I visit the page of a configurable product the first time, I see the drop down menu and I can choose the configurations. when I go out and then back again in the page menu of barianti disappeared. These are still missing even though I visit the page from another computer

in my "Dynamic block" setting i have:

messages,
global_messages,
global_notices,
global_cookie_notice,
right.reports.product.viewed,
product.info

in my Lazy Block i have :

top.links,
cart_sidebar,
catalog.compare.sidebar,
wishlist_sidebar,
welcome,
minicart_head,
right.poll

how can i resolve this problem?

**Comment by GordonLesti** [comment]
Hello @triplexita
The block `product.info` should not be dynamic or lazy.

**Comment by triplexita** [comment]
and how can i disable caching for my custom AW_AUTORELATED block in product page? how can i find the bloc name for exclude this?

**Comment by GordonLesti** [comment]
I guess you are using `Automatic Related Products 2`. I am sorry, I would like to help you, but this is a paid extension with closed source.

**Comment by triplexita** [comment]
No sorry, it not have closed code, but all is as clear and readable.

Il 12/nov/2016 09:39, "Gordon Lesti" <notifications@github.com> ha scritto:
