### ISSUE TITLE
Problem caching prices for taxed/non-taxed zones and multiple currencies

### ISSUE THREAD

**Issue by doctea** [GordonLesti/Lesti_Fpc#266]
I'm running into problems with multiple currencies - or rather, areas with differing tax rules.  I can't seem to find a way to cache based on the 'tax area' being used.

For example, sales to EU countries should have tax applied; sales to elsewhere shouldn't.

If a customer 'A' with a Billing Address/Quote country of 'US' visits a page first, then product details are cached without showing "including VAT".  This 'not showing tax' version will then be incorrectly shown to EU visitors who follow.
If a customer 'B' with a Billing Address/Quote country in the EU visits a page first, then product details are cached showing "including VAT".  This 'showing tax' version will then be incorrectly shown to non-EU visitors who follow.

Even jumping through some hoops to add CountryId to the caching parameters doesn't seem to solve the problem.  Caching on CountryId doesn't seem the best idea either, since (in my situ) there are basically only two unique 'tax areas', while there are hundreds of unique Country Codes that map to them, so the cache would be missing unnecessarily.

In a bit of a rush right now, will come back to investigate this further if there are no suggestions so far!

**Comment by GordonLesti** [comment]
Hello @doctea 
are customer `A` and customer `B` in different customer groups?

**Comment by doctea** [comment]
Hi @GordonLesti, thanks for responding - btw before I go any further I just wanted to say a big THANK YOU for all your hard work on this and dealing with issues!  You are a good man :)

Yes, in this instance both A and B are in different customer groups.  I *think* that I tested it and that it behaved differently when FPC was enabled/disabled, but I'll have to wait until I get back to work tomorrow to double-check that, sorry.  I'll also experiment with having the users in the same and differing customer groups, and see what that turns up.

Is there anything in particular you think I should check over or that might be the cause here?

**Comment by doctea** [comment]
Just came across this fork that seems to add support for caching multiple tax zones without duplicates - I'll give this a try too :) https://github.com/gferon/Lesti_Fpc/commit/a928b60b02be001408858e13a87e9ac6b03dc0c3

**Comment by GordonLesti** [comment]
FPC has an option `Customer Groups` that may help you if the tax or price changes are based on different customer groups.

**Comment by doctea** [comment]
Hi again @GordonLesti ,

I merged the changes made in the fork (https://github.com/gferon/Lesti_Fpc/), and I can't reproduce the reported problem now.  So long as someone else confirms that it works for them too, I'd say that merging gferon's fork into the current Lesti_Fpc main branch will improve Lesti_Fpc's functionality

Thanks again @GordonLesti :).

**Comment by doctea** [comment]
Hi again -- sorry for the long delay in me responding to this, had several other things that have taken away my time.

Just to confirm & help out anyone else struggling with Currency/Location/Taxation caching problems, the patch at https://github.com/gferon/Lesti_Fpc/commit/a928b60b02be001408858e13a87e9ac6b03dc0c3 helps with this problem.  However I had to do several modifications and resolve several problems in order to get it to update when the customer sets a new Shipping Address on their Quote, etc.

Since the functionality for this is spread through my in-house module (handles GeoIP lookups and sets Currencies/Tax rates appropriately), its unfortunately not easy to extract this logic to supply patches back to Lesti_Fpc.

If you think this a useful, important feature then I can do it when I find time, or give some pointers for you Gordon?  

Cheers!
