### ISSUE TITLE
Disable/bypass cache on a per-request basis

### ISSUE THREAD

**Issue by anlutro** [GordonLesti/Lesti_Fpc#267]
Magento EE allows you to bypass its cache by specifying a cookie or query parameter "no_cache". This makes it easy to run benchmarking etc. in production without having to hurt performance for other users.

The code that does this logic is located in `Enterprise_PageCache_Model_Processor::isAllowed`.

As far as I can tell there's no such thing in your module. Would this be easy to implement?

**Comment by GordonLesti** [comment]
Hello @anlutro 
those configs are called [Miss Uri Params](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.6/app/code/community/Lesti/Fpc/etc/config.xml#L269).

**Comment by anlutro** [comment]
Aha. Thanks a lot!
