### ISSUE TITLE
Unirgy GeoIP Extension not working with Lesti Fpc magento 1.9

### ISSUE THREAD

**Issue by deeptecksky** [GordonLesti/Lesti_Fpc#268]
Hi Gordon,

Thanks for this amazing extension and the support you have been providing. We have found an issue with our Magento store. 
I am using Unirgy_GeoIP extension with this Lesti Fpc.
    The problem is, when FPC is turned on GeoIp randomly changes country flags. 
    However, everything works fine if FPC is disabled.
    How do I solve this?

Also, I want to use the event fpc_helper_collect_params to add the resolved storeId of Unirgy_GeoIP module to $parameters array. 
How do I solve this?

Will appreciate any help.
Hoping to be favoured.

**Comment by pszeszko** [comment]
In our example has been used mageworx_geoip extension
 ```
public function collectParams($observer)
    { 
 $parameters = $observer->getEvent()->getParameters();
        $additionalParams = $parameters->getValue();

        $params = array();
        $actions = array('catalog_product_view');

        if (in_array($additionalParams['full_action_name'], $actions)) {
            $params['location'] = Mage::getModel('mageworx_geoip/geoip')->getLocation()->getCode();
        }

        $additionalParams = array_merge($additionalParams, $params);
        $parameters->setValue($additionalParams);
}
```

**Comment by GordonLesti** [comment]
Hello @deeptecksky 
I took a short look at `Unirgy_GeoIP` and it seems like a very clean module that is just providing the two functions `getGeoInstance`, and `getGeoLocation` from the helper `Unirgy_GeoIP_Helper_Data`.
I'm not sure what you are exactly doing with the result of the two functions, but in my eyes you have two options to get it working with FPC.
* If your logic that uses geo data is just showing a country flag in a block, you should just make that block dynamic. This solution ends with a little bit more loading time.
* You can use the event `fpc_helper_collect_params` and add your geo data. Here a small [post](http://gordonlesti.com/edit-cachetags-and-parameters-via-events-in-lesti-fpc-1-3-2/) about the usage of the events in general, but [comment](https://github.com/GordonLesti/Lesti_Fpc/issues/268#issuecomment-261200674) from @pszeszko looks very good. This solution will increase the size of the cache, that produces more MISSes and less HITS.

**Comment by deeptecksky** [comment]
Thanks for your help. Really appreciated.

**Comment by deeptecksky** [comment]
Not getting Country Code from that code of Unirgy_GeoIP. How can i add in which type of params using fpc_helper_collect_params?

**Comment by GordonLesti** [comment]
@deeptecksky can you explain a little bit more detailed? I'm sorry, but I didn't understand the last comment.

**Comment by deeptecksky** [comment]
Means country flags randomly changed by this module geoIp which i have used. this error occurring due to Lest Fpc ?

**Comment by GordonLesti** [comment]
I'm mean a little bit more detailed, cause country flags aren't part of the module `Unirgy_GeoIP`. `Unirgy_GeoIP` is just providing helper functions that your shop is may using.
The information that a country flag is changing randomly let me guess that your shop is may using `Unirgy_GeoIP_Helper_Data::getGeoLocation` to change the source of an image in a template that will be cached by FPC, but that information doesn't help me to find a good solution for your problem.

**Comment by deeptecksky** [comment]
if due to Lesti Fpc, which parameters(Geo data) i have to add ? i have checked with "country".

**Comment by deeptecksky** [comment]
Exact.  My code is here:
if (!Mage::getSingleton('core/session')->getCountryCode()) {
	Mage::helper('ugeoip')->getGeoInstance('GeoIP');
	$geoIp = Mage::helper('ugeoip')->getGeoLocation(true);
	$geoCountryCode = $geoIp->getData('countryCode');
	$geoContinentCode = $geoIp->getData('countryContinent');
	Mage::getSingleton('core/session')->setCountryCode($geoCountryCode);
	Mage::getSingleton('core/session')->setContinentCode($geoContinentCode);
}

Using this code on my template file, i display images on header.
what i have to do for skip GeoIp extension cached by FPC ?

**Comment by GordonLesti** [comment]
I guess you may miss understand a FPC (Full Page Cache). The FPC is not caching the result of the function `getGeoInstance` or `getGeoLocation`, the functions will never be executed if the FPC has a HIT. So you have to say to FPC via event `fpc_helper_collect_params` that it makes a different between two requests with the parameters of your GEO data or you just put your country flag into a separate block that you can make [dynamic or lazy](http://127.0.0.1:8080/what-are-lazy-and-dynamic-blocks-in-lesti-fpc/).

**Comment by deeptecksky** [comment]
Ok. Thank you so much.  I have to put only block name in dynamic or lazy block.
