### ISSUE TITLE
Cached google page?

### ISSUE THREAD

**Issue by ufaarvang** [GordonLesti/Lesti_Fpc#270]
Hello,

We just recently changed our store platform to Magento and upon launching we created 301 for all categories and relevant products. However, by mistake we had a Noindex, nofollow enabled on all pages. Without this knowledge we submitted the new site for re-index in the webmaster console and the page we're reindexed and we lost all our rankings... 

Yet, we discovered the mistake and changed it back into index, follow. However since this, we have on multiple occasions tried to reindex the changed, but when looking into the pages in the google bot simulator it still shows prints the noindex, nofollow on these pages. When creating a new page the google bot reads it correctly with the index, follow. 

So there might be a cache problem on the pages. Responses from the Google forum is, that problem is on our side. 

Is there ANY WAY, that the Lesti Module for Magento is serving google a cached version of our page header? 
See examples in the images attached. 
![noindex](https://cloud.githubusercontent.com/assets/24220619/20661037/ca77098e-b54c-11e6-8dec-54a583388a30.png)
![live-index](https://cloud.githubusercontent.com/assets/24220619/20661038/ca7732e2-b54c-11e6-81ab-00c2e2a705c5.png)

Thanks!

**Comment by GordonLesti** [comment]
Hello @ufaarvang 
no, the module is just caching the HTML what your webshop is sending (except dynamic/lazy blocks). Means if you have flushed FPC after your changes and the problem still occours, the problem is may not solved.

**Comment by ufaarvang** [comment]
Hi GordonLesti,

Thank you very much for your quick answer. 

To my understanding the meta-tags are also part of the HTML.. Seems weird that Google reads an older page than what users are presented. 

U

**Comment by GordonLesti** [comment]
Your screenshop of google webmaster tools is from yesterday. Do you have one that is not older than 45 minutes?
