### ISSUE TITLE
Composer Package not found in firegento

### ISSUE THREAD

**Issue by aftabnaveed** [GordonLesti/Lesti_Fpc#276]
I am trying to install module through composer, but it seems to be not found and longer exists, am I doing any thing wrong here?

https://packages.firegento.com/#!/gordonlesti

**Comment by GordonLesti** [comment]
Hello @aftabnaveed 
spooky, `git://github.com/GordonLesti/Lesti_Fpc.git` is present in [satis.json](https://github.com/magento-hackathon/composer-repository/blob/dde330177299f0048e196c1aa74c33d3fca4a892/satis.json#L238). Seems like [packages.firegento.com](https://packages.firegento.com/) was build in hour ago and Github had also a [problem](https://twitter.com/githubstatus/status/806228936208289792) an hour ago. Maybe the repository was not available as Satis has build.
I guess it is better to create an issue at [composer-repository](https://github.com/magento-hackathon/composer-repository/issues).

**Comment by GordonLesti** [comment]
I have not tested yet, but maybe you can add the repository to your `composer.json`:
```json
{
    "repositories": {
        "gordonlesti-lesti_fpc": {
            "type": "git",
            "url": "https://github.com/GordonLesti/Lesti_Fpc.git"
        },
    }
}
```

**Comment by GordonLesti** [comment]
https://github.com/magento-hackathon/composer-repository/issues/405

**Comment by aftabnaveed** [comment]
thank you @GordonLesti  I did try the VCS type, it did pull the repo, but symlinks still needs to be manually created, I believe it has something to do with Magento's composer repository.

**Comment by GordonLesti** [comment]
I am sorry, I guess we have to wait. The build of [1.4.8](https://travis-ci.org/GordonLesti/Lesti_Fpc/jobs/181775800) also failed, cause `ecomdev/ecomdev_phpunit` could not be found.

**Comment by GordonLesti** [comment]
The packages are present again.
