### ISSUE TITLE
How to call Refresh FPC from other module

### ISSUE THREAD

**Issue by eddetollenaer** [GordonLesti/Lesti_Fpc#279]
Hi,
I wrote a custom import module that works well without the Lesti FPC enabled. When I enable the Lesti FPC module, the product images are broken after importing product info for existing products. 
Refreshing the FPC cache fixes this, so I thought it would be a good idea to call the FPC refresh method after products are imported.

What method do I have to call to refresh the Lesti FPC?
Is it possible to refresh the cache for only one product after a product is imported? If so, what method do I have to call for that?

Kind regards,
Ed

**Comment by GordonLesti** [comment]
Hello @eddetollenaer 
the following code will clean the product with given product ID `$productId`
```php
Mage::getSingleton('fpc/fpc')->clean(sha1('product_' . $productId));
```
but you can also clean more than one product with a given array of product IDs `$productIds`
```php
Mage::getSingleton('fpc/fpc')->clean(
    array_map(
        function($value) {
            return sha1('product_' . $value)
        },
        $productIds
    )
);
```
I hope this will help you.

**Comment by eddetollenaer** [comment]
Thank you. This works!
