### ISSUE TITLE
APCu support

### ISSUE THREAD

**Issue by Hermsi1337** [GordonLesti/Lesti_Fpc#280]
Hey Gordon,
Hey Folks,

do you think it is possible to add support for APCu to Lesti?
Therewith the cached content could be stored in the APCu for faster delivery.

If this idea is complete non-sense, let me know. :rofl: 

Regards,
Hermsi

**Comment by GordonLesti** [comment]
Hello @Hermsi1337 
in general no problem, but you will need a implementation of [Zend_Cache_Backend_Interface](https://github.com/zendframework/zf1/blob/release-1.12.20/library/Zend/Cache/Backend/Interface.php) for [apcu](https://github.com/krakjoe/apcu).

Best Regards
Gordon
