### ISSUE TITLE
Caching module pages

### ISSUE THREAD

**Issue by dhpowrhost** [GordonLesti/Lesti_Fpc#282]
Hi Gordon

Thank you for an awsome cache module. I use it regularly on several pages.

However, there is one thing that i would like to be able to do. I use this module: http://store.redstage.com/products-on-sale.html which creates a page from a cms block and automatically puts all items on sale on that page. However the page is not cached. Is there any way that this page can be cached, and if so, how can i do that?

**Comment by GordonLesti** [comment]
Hello @dhpowrhost 
I gues you may only need to add the layout handle as cacheabe action to the FPC.

**Comment by dhpowrhost** [comment]
@GordonLesti 
thank you.. I found the layout handler and added it to cacheable actions and it WORKS :D
