### ISSUE TITLE
Recursive clean cache

### ISSUE THREAD

**Issue by katop** [GordonLesti/Lesti_Fpc#283]
Hi!

I think I found the problem.

We have 2 links:
site.com/product.html
site.com/product.html?utm_source=123&utm_medium=321

These links provide 2 cache in Lesti.
If I clean it up so the cache:
Mage::getModel('fpc/fpc')->clean(sha1('product_' . $product->getProductId()));

I will clean only the first link, and the second will not be cleared.
How can I clean up recursively?

Thanks!

**Comment by GordonLesti** [comment]
Hello @katop 
I am sorry, but I can reproduce your problem. Both cache entries are getting tagged with the product id by [Lesti_Fpc_Model_Observer_Tags::getCatalogProductViewCacheTags](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.8/app/code/community/Lesti/Fpc/Model/Observer/Tags.php#L98) and both cache entries are getting cleaned with the tag.
