### ISSUE TITLE
Cartpro (mini cart) not updated after going to new page

### ISSUE THREAD

**Issue by Gavrielo** [GordonLesti/Lesti_Fpc#288]
Hi Gordon,

I've had a look at the other issue regarding the Minicart block [Minicart Ajax](https://github.com/GordonLesti/Lesti_Fpc/issues/162), have used the solution for that and it works but have come across another issue.

I have managed to get it updating on same page but when I go to another page (after removing an item) it keeps the previous list of items. Is there any way to make it refresh so that it is always updated on a new page request?

Website i'm using is [here](https://www.gofurnituredirect.co.uk/).

Current FPC settings:
Dynamic blocks:
global_messages,
messages,
global_notices,
global_cookie_notice,
right.reports.product.viewed,
mini.cart.top,
onestepcheckout.daskboard,
cart_minicart,
minicart_head,
cart_sidebar

Refresh actions:
checkout_cart_add,
checkout_cart_delete,
checkout_cart_updatePost,
checkout_cart_ajaxDelete,
checkout_cart_ajaxUpdate,
checkout_cart_updateItemOptions,
catalog_product_compare_add,
catalog_product_compare_clear,
catalog_product_compare_remove,
wishlist_index_add,
wishlist_index_remove,
wishlist_index_update,
wishlist_index_allcart,
wishlist_index_configure,
checkout_onepage_success,
customer_account_login,
poll_vote_add,
cartpro_checkout_cart_ajaxupdate,
cartprooptoins_index_product,
cartpro_checkout_cart_add,
cartpro_checkout_cart_ajaxdelete,
minicart_head,
cart_minicart

Lazy Blocks:
top.links,
cart_sidebar,
catalog.compare.sidebar,
right.reports.product.compared,
wishlist_sidebar,
welcome,
minicart_head,
right.poll,
mini-cartpro,
mini_cartpro_content

**Comment by GordonLesti** [comment]
Hello @Gavrielo 
can you try to move `mini-cartpro` & `mini_cartpro_content` from lazy blocks to dynamic blocks? (make sure that a block is only contained in lazy or dynamic)

**Comment by Gavrielo** [comment]
Hi @GordonLesti ,

I've just moved those to dynamic blocks and they are updating 🥇  
Thanks for your help! 

Kind regards,
Gav
