### ISSUE TITLE
Mini Cart not displaying in Header when FPC is Enabled

### ISSUE THREAD

**Issue by prafull-magento** [GordonLesti/Lesti_Fpc#289]
We are having very crucial problem with one of our shop.
In that some times Mini cart not displaying when we enabled FPC from admin panel System >> Cache Management.

When we refresh cache from admin panel, appearing and again we refresh cache it disappearing.
Any help will be much appreciated.

I also added name of mini cart block in "Dynamic Blocks" and "Lazy Blocks" fields. But still having the issue.

See attached screenshot of code I used in my custom theme with local.xml file for defining the header mini cart.
![minicart-layout](https://cloud.githubusercontent.com/assets/26333936/23811666/f1b50202-05fc-11e7-9253-6540d285a555.png)

**Comment by GordonLesti** [comment]
Hello @prafull-magento 
`header_minicart` seems to be the right block name. Please note, that you should put a block only in dynamic or lazy blocks, never in both.

**Comment by prafull-magento** [comment]
Hi @GordonLesti 
We also tried with that but still mini cart not showing.

Can you tell me that if we can put hole punch for resolving this issue?

**Comment by GordonLesti** [comment]
Do you may have a HTML-minifier enabled, unfortunately FPC can not handle with that.

**Comment by prafull-magento** [comment]
Hi @GordonLesti 

HTML minifier is disabled on the server. But still issue persist.

**Comment by GordonLesti** [comment]
I hope you do not have `header` block or the parent block of your minicart as dynamic or lazy block.

**Comment by prafull-magento** [comment]
Hi @GordonLesti 

YES, I put "header" in the Dynamic blocks field.

Now I removed it and it looks like that mini cart now not hiding again and again.

Thanks a lot for your help to get rid of this.

**Comment by leossmith** [comment]
I am having the same issue, and it is driving me crazy! 

My top cart does not appear although I think that the settings are ok. I also dont have an HTML Minify plugin. 

![header-cart-issue-code](https://user-images.githubusercontent.com/4300876/32370588-58534812-c096-11e7-8fcf-f05a7c2846db.PNG)
![header-cart-issue](https://user-images.githubusercontent.com/4300876/32370589-58a6cfa0-c096-11e7-9553-503d24b3c9e8.PNG)
