### ISSUE TITLE
Enable Lesti only for one specific store-view

### ISSUE THREAD

**Issue by dhpowrhost** [GordonLesti/Lesti_Fpc#290]
I would like to enable Lesti for one specific store-view. Is this possible with Lesti?

**Comment by GordonLesti** [comment]
Hello @dhpowrhost
Yes & no, a cache is a global thing for Magento. So FPC is enabled for all store-views, but you just need to remove the cacheable actions in the configs of FPC for all except the specific store-view. I hope this will help you.

**Comment by dhpowrhost** [comment]
Thank you. That was precisely the info i needed.. :)
