### ISSUE TITLE
Dont Cache Footer

### ISSUE THREAD

**Issue by JamesSimpson** [GordonLesti/Lesti_Fpc#292]
Hi Gordon,

I've been trying to make it so the plugin doesnt cache the footer of the page, as there's a few bits of dynamic content in there, but for some reason, when I put "footer" in Dynamic Blocks, they are still cached?

I have also tried putting "footer" in Bypass Handles, this doesn't seem to work either. Am i putting them in the correct sections?

**Comment by GordonLesti** [comment]
Hello @JamesSimpson
* I recommend always to make only blocks without children dynamic or lazy. Think of a tree for the layout, it is always better to make only leafs dynamic or lazy.
* The `footer` block is also cached by Magentos block cache.
