### ISSUE TITLE
How to add custom Helper class/function in refresh action

### ISSUE THREAD

**Issue by dev2jbsols** [GordonLesti/Lesti_Fpc#293]
Hello,

I have created a custom module with some logic for product price discount, but when I enable Lesti-FPC cache plugin and visit frontend then it is not showing me updated product price with discount.

How to add my custom module helper class/function in refresh block so that the product price (with my custom logic) display correct price on frontend.
OR how to not cache catalog/price.phtml? 

Thank You.

**Comment by GordonLesti** [comment]
Hello @dev2jbsols 
can you tell a little bit more about the logic of your price discount? Is it depending on the the customer group or locale or something like that?
Cause FPC can not render `price.phtml` on a cached request. The product model doesn't exist yet, when FPC sends response to the user. The only option is to cache different versions of a product page with FPC.

**Comment by dev2jbsols** [comment]
Hello GordonLesti,

Thanks for reply.
In my magento store price calculation is based on another server not from catalog product price, so that catalog price rule not apply directly. For this I customized price.phtml accordingly that check if there is any catalog price enable or all condition matched then price of product showing with discount. My Logic works well without FPC plugin but when I enable Lesti-FPC then it is not working properly, 

For Example : when I visit frontend (not logged in) in case no catalog price rule apply on product then product price display without discount which is proper but when I login as customer then there should be display discount with price but it is not display to customer. When I remove cache from admin and refresh frontend then discounted price visible to customer, and now if I logged out still discounted price  displaying on product which is not proper.  

Please reply.

**Comment by GordonLesti** [comment]
But it changes only for logged in and not logged in users? Or are there different discounts depending on the logged in user?

**Comment by dev2jbsols** [comment]
As catalog price rule works in magento. My logic only takes discount amount (fixed/percent) from catalog price rule when all condition match (website, customer, product) and display discounted price on product which are coming from another server.

**Comment by GordonLesti** [comment]
That is tricky. If you wouldn't have it customer based, instead customer group based, you could use the config FPC settiing `Customer Groups`. But if it is customer based, I see no easy solution for your problem.

**Comment by dev2jbsols** [comment]
It is not customer or customer group based, I just want to refresh price.phtml on every page load.

**Comment by GordonLesti** [comment]
I am sorry, in my eyes is there no way to get it work with Fpc and caching of `catalog_product_view`.
