### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by Baachi** [GordonLesti/Lesti_Fpc#294]
Hey all!

I would like to monitor the misses/hits of the fpc, through [munin](http://munin-monitoring.org/). 
But i don't see any statistic from this bundle, any ideas?

**Comment by GordonLesti** [comment]
Hello @Baachi 
you could maybe write your own little module that depends on FPC and use the events [fpc_http_response_send_before](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.9/app/code/community/Lesti/Fpc/Model/Observer.php#L80) and [fpc_save_data_before](https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.9/app/code/community/Lesti/Fpc/Model/Fpc.php#L92). I hope this answer helps you.
Best Regards
Gordon
