### ISSUE TITLE
(mini cart) not updated after going to new page with https://themeforest.net/item/porto-ultimate-responsive-magento-theme/9725864

### ISSUE THREAD

**Issue by ParimalMageDev** [GordonLesti/Lesti_Fpc#295]
Hi Gordon,

I have removed all blocks from lazy to dynamic section still i am facing this issue on my porto theme, can you please guide me on this?

**Comment by GordonLesti** [comment]
Hello @ParimalMageDev 
you removed all blocks from lazy or dynamic blocks?

**Comment by ParimalMageDev** [comment]
from "Lazy Blocks" !

**Comment by GordonLesti** [comment]
A sorry, I miss readed. Are you sure that your theme uses the same default block names cor minicart as RWD?

**Comment by ParimalMageDev** [comment]
Mostly but how can I confirm that, can you please tell me?

**Comment by GordonLesti** [comment]
Did you read [How to find the name in layout of a block in Magento](http://gordonlesti.com/how-to-find-the-name-in-layout-of-a-block-in-magento/)? I hope this will help you.

**Comment by ParimalMageDev** [comment]
Yes i have read it and update some block as related to theme but no luck.

**Comment by GordonLesti** [comment]
I hope you flushed hole Magento cache afterwards? I am sorry, I would like to help you, but your theme is closed source.

**Comment by ParimalMageDev** [comment]
I hope you flushed hole Magento cache afterwards? => Yes

**Comment by ParimalMageDev** [comment]
If you want I can give you dev site url?

**Comment by GordonLesti** [comment]
Please contact me via email.

**Comment by ParimalMageDev** [comment]
Ok thanks Gordon!

**Comment by GordonLesti** [comment]
`minicart` and `sticky.minicart` are the dynamic blocks for the theme
