### ISSUE TITLE
Clearing cache depending on the date

### ISSUE THREAD

**Issue by gety9** [GordonLesti/Lesti_Fpc#296]
We have a sale block created as CMS>static block
```
<div class="special_inner">
<p>Limited Time Only. Order by [MON] [DAY]</p>
</div>
```

This is the function generating the MON and DAY values:
```
    public function getMonthlySpecialDetail() {
        $blockHtml = Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('monthly_special_block')->toHtml();
        $blockHtml = str_replace('[SPECIAL_TITLE]', $this->getMonthlySpecialTitle(), $blockHtml);
        $cdate = Mage::getModel('core/date')->timestamp(time());
        $dayOfMonth = date("j", $cdate);
        $month = date("M", $cdate);
        $blockHtml = str_replace('[MON]', $month, $blockHtml);
        if($dayOfMonth <= 5) {
            $dayOfMonth = '5th';
        }
        elseif($dayOfMonth <= 10) {
            $dayOfMonth = '10th';
        }
        elseif($dayOfMonth <= 15) {
            $dayOfMonth = '15th';
        }
        elseif($dayOfMonth <= 20) {
            $dayOfMonth = '20th';
        }
        elseif($dayOfMonth <= 25) {
            $dayOfMonth = '25th';
        }
        elseif($month == 'Feb') {
            $dayOfMonth = '28th';
        }
        elseif(in_array($month, array('Apr','Jun', 'Sep', 'Nov'))) {
            $dayOfMonth = '30th';
        }
        else {
            $dayOfMonth = '31st';
        }
        $blockHtml = str_replace('[DAY]', $dayOfMonth, $blockHtml);
        return $blockHtml;
    }
```

Block changes every 5 days, (and 3-6 days the last day of the month)

It's saying - "Limited Time Only. Order by May 5th" - for May 1st till May 5th
"Limited Time Only. Order by May 10th" - for May 6th till May 10th
etc

What's the best way to clear cache in that case?

**Comment by GordonLesti** [comment]
Hello @gety9 
I do not understand why you do this replacing stuff. I guess your date-IF is also not working for leap-years. But I hope the post [Dynamic or lazy blocks in a CMS page with Lesti_FPC](https://gordonlesti.com/dynamic-or-lazy-blocks-in-a-cms-page-with-lesti-fpc/) will help you.

**Comment by gety9** [comment]
Gordon,

Thank you for your reply,

Please tell me if i understand that right:
If i would use Dynamic or lazy block, the block will display date correctly, but i would not fully utilize the FPC. (pages will be a little slower).

Is it better to create cron task that will clear the cache when the date in sale block is changed - on the 6th of the month at 00:05am, on the 11th  of the month at 00:05am etc.

**Comment by GordonLesti** [comment]
The dat will be correct, but this specific block will be rendered on every request. Your cron solution is also possible I would say.
Why aren't you doing those stuff on the client side with Javascript?
