### ISSUE TITLE
New features for Lesti FPC

### ISSUE THREAD

**Issue by Mobecls** [GordonLesti/Lesti_Fpc#301]
We've added new options for the extension:

- clean cache by page;
- clean cache via cron.

If you need these features contact us by e-mail ([Mobecls](https://mobecls.com/))

**Comment by marcopolo88** [comment]
why an email? a pull request please
thx

**Comment by gety9** [comment]
@Mobecls any plans for PR?

Or you keeping it to yourself?

**Comment by Mobecls** [comment]
Not really, we've sent it directly to Gordon to review and merge. I'm not sure if PR will work as we were not updating it for about a year.

Let me check on next week.

**Comment by manezaf8** [comment]
So what happened to that fix ?

**Comment by Mobecls** [comment]
guys, I think it wasn't reviewed and accepted by Gordon. 
If you would like to - email me - I'll send you the fix.

**Comment by manezaf8** [comment]
That would be great,
 please send it to bmaneza@gmail.com.
