### ISSUE TITLE
Clearing custom blocks

### ISSUE THREAD

**Issue by mortenjakobsen** [GordonLesti/Lesti_Fpc#305]
Is there a way to clear a custom block ?

It seems it's possible to clear products cache like this:

```
// Clears all products
$this->_getFpc->clean(sha1('product'));

// Clears product id 2
$this->_getFpc->clean(sha1('product_2'));
```
I would like to clear my custom blocks the same way, but that doesn't seem to work.

Any input for this?

**Comment by gety9** [comment]
@mortenjakobsen 

Did you find the solution for this?

I need a way to clear cache of specific block not the full page.

**Comment by mortenjakobsen** [comment]
My colleague ended up implementing the fix... If I recall correctly, he made some changes to the save observer, and added custom handles for the blocks when saved, so we had the ability to clear this way.
