### ISSUE TITLE
installed fpc using modman and get blank page with the following error

### ISSUE THREAD

**Issue by vicding** [GordonLesti/Lesti_Fpc#318]
The error message is: 
`AH01071: Got error 'PHP message: PHP Fatal error:  Call to a member function addStorageType() on boolean in includes/src/__default.php on line 11656\n'`

The code is 
`       $messageBlock = $action->getLayout()->getMessagesBlock();
        foreach (array('catalog/session', 'checkout/session', 'customer/session') as $storageType) {
            $storage = Mage::getSingleton($storageType);
            if ($storage) {
                $messageBlock->addStorageType($storageType);
                $messageBlock->addMessages($storage->getMessages(true));
            }
        }`

I am on ubuntu 16.04 + nginx + php7.0-fpm with magento 1.9.3.7

There is no custom fpc configure done yet. Can you please take a look?

**Comment by GordonLesti** [comment]
Hello @vicding 
I hope this [issue](https://github.com/GordonLesti/Lesti_Fpc/issues/240) may helps you.

Best Regards
Gordon

**Comment by vicding** [comment]
Many thanks! this solved my issue.
