### ISSUE TITLE
How to add dynamic blocks to home page magento 1.9

### ISSUE THREAD

**Issue by mmannanmasood** [GordonLesti/Lesti_Fpc#322]
I have a block added using the cms page in admin panel. 
{{block type="core/template" name="home-page-main-block" block_id="home_featured_block" template="page/blocks/home_page_main_block.phtml"}} 

I saw a post where you said to add this block in the cms_page_view handle too, I followed your instructions but still it didnt worked, can you please guide me what I am doing wrong. In my local.xml I have added:

    <cms_page_view>
        <refernence name="content">
            <block type="core/template" name="home-page-main-block" as="home-page-main-block" template="page/blocks/home_page_main_block.phtml"/>
        </refernence>
    </cms_page_view>

also there you said to add it in the local.xml in the not visible way, can you please elaborate it.

Thanks.

**Comment by Baachi** [comment]
You have a typo in `reference`. Maybe this is your fault?

**Comment by mmannanmasood** [comment]
@Baachi what an eagle eye you have, Thanks.
