### ISSUE TITLE
Catalog Price Rules compatibility

### ISSUE THREAD

**Issue by timsergeev** [GordonLesti/Lesti_Fpc#33]
The problem goes to Catalog Price Rules. Long story short, when FPC is enables everything works perfectly, all pages are cached and no problem, but when Catalog Price Rules is active and automatically change the price (crontab) the old price still cached in catalog. End when the client is looking at the catalog – they see cached prices (old ones) instead of real ones. But when they add products to cart the real price reveal itself (which is different). Is there is a way to flush a cache when Catalog Price Rules are in action?

**Comment by ProxiBlue** [comment]
ref: https://github.com/GordonLesti/Lesti_Fpc/pull/272

**Comment by ProxiBlue** [comment]
Additional note: The update, to mark the caches as invalidate does not solve this issue, as noted by OP.
The caches are marked as invalidated, upon apply, and clearing those caches would not necessarily 'kick in' the discounts ON SCHEDULE. The issue remains that when the scheduled discount rule date is reached, the sites would still not show the discounts, as the cached pages at that time would not check for the reached date, and effect a cache clear.

**Comment by ProxiBlue** [comment]
What would be needed is a cron job, that looks at catalog price rules dates, and if any products are found to activate of 'the day', cache for those products should be cleared.
