### ISSUE TITLE
Fatal error on version 1.4.9

### ISSUE THREAD

**Issue by ananth-iyer** [GordonLesti/Lesti_Fpc#338]
Error message:

> Fatal
> error: Class 'Lesti_Fpc_Model_Fpc_CacheItem' not found in /var/www/html/dev.eyelashextensions.com/eyelash/app/code/community/Lesti/Fpc/Model/Observer.php on line 137

**Comment by GordonLesti** [comment]
Class:
https://github.com/GordonLesti/Lesti_Fpc/blob/1.4.9/app/code/community/Lesti/Fpc/Model/Fpc/CacheItem.php#L6

**Comment by ananth-iyer** [comment]
I know **CacheItem.php** class is there, on local server it is working properly. But after deployed on staging server it shows the above error.

**Comment by GordonLesti** [comment]
But your answer makes it pretty clear, where you have to search for the reason or?

**Comment by ananth-iyer** [comment]
it's working properly

**Comment by ananth-iyer** [comment]
Kindly suggest me best way configure `app/etc/fpc.xml.sample` file
