### ISSUE TITLE
Full page cache and different tax rates

### ISSUE THREAD

**Issue by gferon** [GordonLesti/Lesti_Fpc#35]
Hi Gordon,

I noticed an issue with your implementation. We have multiple tax rates, so the catalog prices change depending of the shipping address of the currently logged customer.

When this happens, if a page is not already cached, it will be stored (obviously) but this lead to pages with different prices tax rates.

Any pointers on how I could implement a check against the currently logged customer, or add a tax rate parameter in the URL hash?

**Comment by srmobile** [comment]
I have an issue where some users aren't charged tax at all, is it possible that this FPC is responsible? I cannot reproduce the problem, is there anyway to have the FPC ignore anything to do with taxes? Thank you, SR

**Comment by GordonLesti** [comment]
@srmobile maybe it would help in your case to enable just `User Groups` in the configs of Fpc. If that does not help, you can use the event `fpc_helper_collect_params` https://github.com/GordonLesti/Lesti_Fpc/blob/1.3.5/app/code/community/Lesti/Fpc/Helper/Data.php#L102

**Comment by srmobile** [comment]
@GordonLesti thanks for your response, can you point me where the config files are located? I did a grep for User Groups and it didn't return anything. Many thanks!

**Comment by GordonLesti** [comment]
https://gordonlesti.com/projects/lestifpc/#configurations
