### ISSUE TITLE
Magento mini cart on top issue

### ISSUE THREAD

**Issue by LakshmiMaheshBabu** [GordonLesti/Lesti_Fpc#58]
Hi, all, I m having issue with mini cart on right top of my template which does not stay dynamic, i.e, FPC caches it. When product is added, it changes, but when I go back to homepage, homepage does not reflect the items, this is happening with all the pages, i.e, minicart status of that particular page does not carry forward to next page, be it homepage or any other page. Please help how to solve this.

**Comment by chandrumcd** [comment]
Hi,

I am facing similar kind of issue but cart is cached even after new customer logs in only happens with mini cart.

cart is not flushing out.

Please help me to sort this out.

Regards,
Chandrasekar

**Comment by surgyelan** [comment]
Anyone facing this problem with Magento 1.9 should add the following events:

checkout_cart_updateItemOptions,
checkout_cart_ajaxDelete,
checkout_cart_ajaxUpdate

If you are in trouble finding the right event some hints for you: 
edit /app/Mage.php (no other way to gather all events, this shold be done in dev. environmet only)

add the following line in public static function dispatchEvent($name, array $data = array()) {..}

Mage::log($name, null, 'events.log', true);

Check the generated events and look for controller_action_postdispatch_.*
The Lesti event name is the .* part.

For example for this event:
controller_action_postdispatch_checkout_cart_ajaxUpdate

this should be added to the event list:
checkout_cart_ajaxUpdate

Cheers,

Leon
