### ISSUE TITLE
Disable Cache on Upsell Block (Magento 1.7.0)

### ISSUE THREAD

**Issue by tylers-username** [GordonLesti/Lesti_Fpc#71]
I've tried adding both product.info.upsell and upsell_products to the dynamic blocks in Lest::FPC configuration but am seeing the same products displayed each time.

**Comment by shilak123** [comment]
i am facing issue on product detail page with description dynamic block, if one product page have loaded then same description and review seems same on all product detail due to lesti fpc module page. plz give any suggestion to resolve this
