### ISSUE TITLE
Randomly generating 404 pages on category pages...

### ISSUE THREAD

**Issue by hidonet** [GordonLesti/Lesti_Fpc#74]
I'm using Lesti FPC with Redis backend. Category pages generating 404 pages and caching it. When I open same url from https:// clearing cache and regenerating cache for that category.
Or If I execute flushall on redis server every category page is working.

How do I fix this ?

**Comment by Danustyle** [comment]
hi all , solution for this problem ? i get 404 in some categories , how i can debug ?

thx

**Comment by salubrium** [comment]
We had the same issue when using Amasty Improved Navigation, the issue is the controller isn't setting the httpResponseCode with a 404, rather it was just setting a 404 header.

Here's our small diff fix


@@ -27,6 +27,7 @@ class Amasty_Shopby_Model_Observer
                 // no way to tell controler to show 404, do it manually
                 $controller->getResponse()->setHeader('HTTP/1.1','404 Not Found');
                 $controller->getResponse()->setHeader('Status','404 File not found');
+               $controller->getResponse()->setHttpResponseCode(404);
         
                 $pageId = Mage::getStoreConfig(Mage_Cms_Helper_Page::XML_PATH_NO_ROUTE_PAGE);
                 if (!Mage::helper('cms/page')->renderPage($controller, $pageId)) {

**Comment by GordonLesti** [comment]
@salubrium Thank you very much. Sounds like a possible reason to me.

**Comment by bbtimx** [comment]
Hello,

I randomly had the same problem. Some category pages show 404 error page not found.
After deleting my cookies all works fine but after some time the error comes up again.

Tried this too but without any 404 error:

```
if (strpos($body, '404')!==false) {
    Mage::log(Mage::app()->getRequest()->getRequestUri(), null, 'fpc_404.log');
}
```
I´m using the latest Magento CE 1.9.3.7 and Redis 3.2.11 64 bit with 3 different instances for Lesti_Fpc, Session and Cache Storage.

**Comment by rvelhote** [comment]
Is anyone affected by this using `MageWorx_GeoIP` and/or `MageWorx_StoreSwitcher`? I've managed to replicate this error quite consistently in our website with CMS pages and those two modules. Upon disabling them I've had no issues.

I think this problem, at lease in my case, might be related to switching store views where a URL doesn't existing to a store view where the URL exists.

I'm trying to come up with a solution that does not require disabling those modules. Also, I'm using the file cache not Redis.
