### ISSUE TITLE
Cart block in header is cached!

### ISSUE THREAD

**Issue by ADDISON74** [GordonLesti/Lesti_Fpc#88]
1) Visit Product A and add it to cart. You will be redirected to Cart page if option is enabled and look at the Cart block in header. It shows correctly 1 product in cart. Click [Continue Shopping] button you will go back to your product added to cart. Look again to Cart block in header. Now Cart is empty.

2) Next visit Product B. Look at Cart block in header it says 1 product in cart which is correct. Click [Add to Cart]. You will be redirected to Cart page. Cart block now says 2 products in cart. Click [Continue Shopping] button and will go back to your Product B page. Look again to Cart block in header. Cart says 1 product in cart.

3) Visit Products C and D, add them to cart. In Cart page right click on product links and open them in new tabs. Look at Cart block and see different numbers of products in Cart. This is not correct at all.

Conclusion: Cart block is cached in header. When you visit a product this block will stamp as it is from now on in your navigation inside the website. If you go back to that page, incorrect number of products will be shown (if products were added to cart). But for Cart page it shows correct information, I guess because the whole page is not cached there.

Thank you.

**Comment by GordonLesti** [comment]
https://gordonlesti.com/what-are-lazy-and-dynamic-blocks-in-lestifpc/
