### ISSUE TITLE
Customer session messages are not displayed

### ISSUE THREAD

**Issue by aurmil** [GordonLesti/Lesti_Fpc#92]
As discussed / debugged via emails:

CMS pages rendering calls Mage_Cms_Helper_Page :: renderPage() which calls Mage_Cms_Helper_Page :: _renderPage() which does

```php
...
foreach (array('catalog/session', 'checkout/session', 'customer/session') as $storageType) {
    ...
    $messageBlock->addStorageType($storageType);
    ...
}
...
```

and customer/session namespace is not managed by your module

bug case: try to add and display a message in customer session on a CMS page (eg: home page)
message is displayed at first page load but never again when page was cached

**Comment by GordonLesti** [comment]
should be fine since https://github.com/GordonLesti/Lesti_Fpc/commit/2410ade3b4641208e284ea9f4ce4c0e109e46719
