### ISSUE TITLE
Invalid response

### ISSUE THREAD

**Issue by devzorg** [GordonLesti/Lesti_Fpc#94]
Magento shows me an error that I can't understand it reproduce only then <fpc> tag declared in fpc.xml or in local.xml

http://take.ms/Rl7kZ

**Comment by GordonLesti** [comment]
@devzorg It seems that the Fpc can't save, cause your Redis server returns a invalid response.

**Comment by devzorg** [comment]
I don't know the reason and can't debug it, just got this then add to settings <fpc><backend...> settings

**Comment by GordonLesti** [comment]
@devzorg start debugging at this point https://github.com/colinmollenhour/credis/blob/1.5/Client.php#L999 (depending on your credis version)

**Comment by GordonLesti** [comment]
@devzorg Can I close this issue?

**Comment by devzorg** [comment]
Perhaps it relates to #101
