### ISSUE TITLE
disabaling the header cache

### ISSUE THREAD

**Issue by masoudjahromi** [GordonLesti/Lesti_Fpc#96]
Hello Dear sir/madam:

Please guide me and let me know how can I disable the header cache

Thank you for the time and consideration. Your quick response will be highly appreciated.

Yours faithfully,
Masoud

**Comment by GordonLesti** [comment]
Hello,
the http-header won't be cached. If you mean the header block. You can't make the hole header block dynamic, but it's children if they are leafs in the layout tree. Please see https://gordonlesti.com/what-are-lazy-and-dynamic-blocks-in-lestifpc/

Best Regards
Gordon
