### ISSUE TITLE
FPC with Add to Cart ajax session request

### ISSUE THREAD

**Issue by michihu** [GordonLesti/Lesti_Fpc#97]
hi,

i am using lesti fpc quite often and really like the function. Today I came on a new store over anissue i dont find a solution for.

it uses the sm-cart Add To Cart Ajax module. If I enable FPC you are not able to add products to cart:

The error I see with fpc enabled is:

Uncaught TypeError: Cannot read property 'get' of undefined
if($.session.get("session"+proId) != null ){

or

TypeError: $.session is undefined

this is the code of the addtocart.phtml that is asking for a session:

if($.session.get("session"+proId) != null ){
				cartQty = $.session.get("session"+proId);
				if(eval(maxQty - qtyStock) <= 0){
					temp = eval(maxQty-cartQty);
				}else{
					temp = eval(qtyStock-cartQty);
				}
				temp1 = eval(temp-curQty);
				if(temp1 < 0){
					re = 0;
					alert("Please, enter quantity > Min: "+minQty+', and < Max: '+maxQty+', and Inventory: '+qtyStock);

Anybody has an idea how to fix this? thanks :)

**Comment by GordonLesti** [comment]
Hello @michihu 
* is that javascript?
* please try to paste code more readable, maybe this can help you https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks
* please protect yourself, cause you paste code of a paid extension

**Comment by michihu** [comment]
Hi, the code giving the error is called from the themes addtocart.phtml

the function $.session is coming from the modules jquery.session.js file

heres the code that calls it in the addtocart.phtml

```
		// validate simple product
		$('.btn-cart-single').bind("click",function(){	
			re = 1;
			proId = $("#proId").val();
			curQty = $('#qty').val();
			minQty = $('#min_qty_stock').val();
			maxQty = $('#max_qty_stock').val();
			qtyStock = $('#qty_stock').val();
			if(minQty==''&&maxQty==''&&qtyStock==''){
				alert('Please, select item');
				return false;
			}
			if(eval(maxQty - qtyStock) < 0){
				temp = maxQty;
			}else{
				temp = qtyStock;
			}
			if(eval(temp - curQty) < 0){
				re = 0;
				alert('Please, enter quantity > Min: '+minQty+' and < Max: '+maxQty+' and < Inventory: '+qtyStock);
				return false;
			}
			if(eval(curQty - minQty) < 0){
				re = 0;
				alert('Please, enter quantity > Min: '+minQty+' and < Max: '+maxQty+' and < Inventory: '+qtyStock);
				return false;
			}
			if($.session.get("session"+proId) != null ){
				cartQty = $.session.get("session"+proId);
				if(eval(maxQty - qtyStock) <= 0){
					temp = eval(maxQty-cartQty);
				}else{
					temp = eval(qtyStock-cartQty);
				}
				temp1 = eval(temp-curQty);
				if(temp1 < 0){
					re = 0;
					alert("Please, enter quantity > Min: "+minQty+', and < Max: '+maxQty+', and Inventory: '+qtyStock);
					return false;
				}
			}
			//end check qty of product
			if(re==1){
				productAddToCartForm.submit(this)
				$.session.set("session"+proId,curQty);
			} 
```

**Comment by GordonLesti** [comment]
Hello @michihu I'm sorry, but I don't know why `$.session` is undefined. Please contact the developers of the paid extension.

**Comment by michihu** [comment]
thanks a lot. it didnt make any sense. everything is working when i simply comment that session out. looks like its not needed
