### ISSUE TITLE
Onepage checkout issues

### ISSUE THREAD

**Issue by epiblue** [GordonLesti/Lesti_Fpc#98]
Hello,

First of all, great plugin and works as a Charm

I have one small issue and don't understand what I should add to avoid this issue.

The thing is, that I have Buy as a Guest enabled, and when I'm trying to make a purchase as a guest, the page is asking me for the Password, witch shouldn't happen. 

I would like to know how to by pass this? Or if it's not posible to bypass, how to add cache exeption for the domain.com/checkout/onepage/ ?

Thank you very much,

**Comment by GordonLesti** [comment]
Hello @epiblue Fpc didn't cache checkout pages, if you didn't add checkout as cacheable

**Comment by epiblue** [comment]
Hello @GordonLesti thank you for your fast reply,

I will investigate further then. 

And you're correct, I disabled your awesome plugin and the problem persists. 

Something else is failing... Probably the checkout Ajax page.

Thanks,
